// pt-BR currency data pinned from Node 26.3.0 / ICU 78.3 / CLDR 48.0.
// Currency membership comes from ISO 4217 List One (2026-01-01): active
// country currencies plus XDR, excluding metals, testing, no-currency,
// fund, accounting-unit, and indexed-unit codes.
pub const Currency = struct {
    numeric: u32,
    prefix: []const u8,
    fraction_digits: u8,
};

pub const currencies = [_]Currency{
    .{ .numeric = 8, .prefix = "ALL\xC2\xA0", .fraction_digits = 0 }, // ALL
    .{ .numeric = 12, .prefix = "DZD\xC2\xA0", .fraction_digits = 2 }, // DZD
    .{ .numeric = 32, .prefix = "ARS\xC2\xA0", .fraction_digits = 2 }, // ARS
    .{ .numeric = 36, .prefix = "AU$\xC2\xA0", .fraction_digits = 2 }, // AUD
    .{ .numeric = 44, .prefix = "BSD\xC2\xA0", .fraction_digits = 2 }, // BSD
    .{ .numeric = 48, .prefix = "BHD\xC2\xA0", .fraction_digits = 3 }, // BHD
    .{ .numeric = 50, .prefix = "BDT\xC2\xA0", .fraction_digits = 2 }, // BDT
    .{ .numeric = 51, .prefix = "AMD\xC2\xA0", .fraction_digits = 2 }, // AMD
    .{ .numeric = 52, .prefix = "BBD\xC2\xA0", .fraction_digits = 2 }, // BBD
    .{ .numeric = 60, .prefix = "BMD\xC2\xA0", .fraction_digits = 2 }, // BMD
    .{ .numeric = 64, .prefix = "BTN\xC2\xA0", .fraction_digits = 2 }, // BTN
    .{ .numeric = 68, .prefix = "BOB\xC2\xA0", .fraction_digits = 2 }, // BOB
    .{ .numeric = 72, .prefix = "BWP\xC2\xA0", .fraction_digits = 2 }, // BWP
    .{ .numeric = 84, .prefix = "BZD\xC2\xA0", .fraction_digits = 2 }, // BZD
    .{ .numeric = 90, .prefix = "SBD\xC2\xA0", .fraction_digits = 2 }, // SBD
    .{ .numeric = 96, .prefix = "BND\xC2\xA0", .fraction_digits = 2 }, // BND
    .{ .numeric = 104, .prefix = "MMK\xC2\xA0", .fraction_digits = 0 }, // MMK
    .{ .numeric = 108, .prefix = "BIF\xC2\xA0", .fraction_digits = 0 }, // BIF
    .{ .numeric = 116, .prefix = "KHR\xC2\xA0", .fraction_digits = 2 }, // KHR
    .{ .numeric = 124, .prefix = "CA$\xC2\xA0", .fraction_digits = 2 }, // CAD
    .{ .numeric = 132, .prefix = "CVE\xC2\xA0", .fraction_digits = 2 }, // CVE
    .{ .numeric = 136, .prefix = "KYD\xC2\xA0", .fraction_digits = 2 }, // KYD
    .{ .numeric = 144, .prefix = "LKR\xC2\xA0", .fraction_digits = 2 }, // LKR
    .{ .numeric = 152, .prefix = "CLP\xC2\xA0", .fraction_digits = 0 }, // CLP
    .{ .numeric = 156, .prefix = "CN\xC2\xA5\xC2\xA0", .fraction_digits = 2 }, // CNY
    .{ .numeric = 170, .prefix = "COP\xC2\xA0", .fraction_digits = 0 }, // COP
    .{ .numeric = 174, .prefix = "KMF\xC2\xA0", .fraction_digits = 0 }, // KMF
    .{ .numeric = 188, .prefix = "CRC\xC2\xA0", .fraction_digits = 2 }, // CRC
    .{ .numeric = 192, .prefix = "CUP\xC2\xA0", .fraction_digits = 2 }, // CUP
    .{ .numeric = 203, .prefix = "CZK\xC2\xA0", .fraction_digits = 2 }, // CZK
    .{ .numeric = 208, .prefix = "DKK\xC2\xA0", .fraction_digits = 2 }, // DKK
    .{ .numeric = 214, .prefix = "DOP\xC2\xA0", .fraction_digits = 2 }, // DOP
    .{ .numeric = 222, .prefix = "SVC\xC2\xA0", .fraction_digits = 2 }, // SVC
    .{ .numeric = 230, .prefix = "ETB\xC2\xA0", .fraction_digits = 2 }, // ETB
    .{ .numeric = 232, .prefix = "ERN\xC2\xA0", .fraction_digits = 2 }, // ERN
    .{ .numeric = 238, .prefix = "FKP\xC2\xA0", .fraction_digits = 2 }, // FKP
    .{ .numeric = 242, .prefix = "FJD\xC2\xA0", .fraction_digits = 2 }, // FJD
    .{ .numeric = 262, .prefix = "DJF\xC2\xA0", .fraction_digits = 0 }, // DJF
    .{ .numeric = 270, .prefix = "GMD\xC2\xA0", .fraction_digits = 2 }, // GMD
    .{ .numeric = 292, .prefix = "GIP\xC2\xA0", .fraction_digits = 2 }, // GIP
    .{ .numeric = 320, .prefix = "GTQ\xC2\xA0", .fraction_digits = 2 }, // GTQ
    .{ .numeric = 324, .prefix = "GNF\xC2\xA0", .fraction_digits = 0 }, // GNF
    .{ .numeric = 328, .prefix = "GYD\xC2\xA0", .fraction_digits = 2 }, // GYD
    .{ .numeric = 332, .prefix = "HTG\xC2\xA0", .fraction_digits = 2 }, // HTG
    .{ .numeric = 340, .prefix = "HNL\xC2\xA0", .fraction_digits = 2 }, // HNL
    .{ .numeric = 344, .prefix = "HK$\xC2\xA0", .fraction_digits = 2 }, // HKD
    .{ .numeric = 348, .prefix = "HUF\xC2\xA0", .fraction_digits = 0 }, // HUF
    .{ .numeric = 352, .prefix = "ISK\xC2\xA0", .fraction_digits = 0 }, // ISK
    .{ .numeric = 356, .prefix = "\xE2\x82\xB9\xC2\xA0", .fraction_digits = 2 }, // INR
    .{ .numeric = 360, .prefix = "IDR\xC2\xA0", .fraction_digits = 0 }, // IDR
    .{ .numeric = 364, .prefix = "IRR\xC2\xA0", .fraction_digits = 0 }, // IRR
    .{ .numeric = 368, .prefix = "IQD\xC2\xA0", .fraction_digits = 0 }, // IQD
    .{ .numeric = 376, .prefix = "\xE2\x82\xAA\xC2\xA0", .fraction_digits = 2 }, // ILS
    .{ .numeric = 388, .prefix = "JMD\xC2\xA0", .fraction_digits = 2 }, // JMD
    .{ .numeric = 392, .prefix = "JP\xC2\xA5\xC2\xA0", .fraction_digits = 0 }, // JPY
    .{ .numeric = 398, .prefix = "KZT\xC2\xA0", .fraction_digits = 2 }, // KZT
    .{ .numeric = 400, .prefix = "JOD\xC2\xA0", .fraction_digits = 3 }, // JOD
    .{ .numeric = 404, .prefix = "KES\xC2\xA0", .fraction_digits = 2 }, // KES
    .{ .numeric = 408, .prefix = "KPW\xC2\xA0", .fraction_digits = 0 }, // KPW
    .{ .numeric = 410, .prefix = "\xE2\x82\xA9\xC2\xA0", .fraction_digits = 0 }, // KRW
    .{ .numeric = 414, .prefix = "KWD\xC2\xA0", .fraction_digits = 3 }, // KWD
    .{ .numeric = 417, .prefix = "KGS\xC2\xA0", .fraction_digits = 2 }, // KGS
    .{ .numeric = 418, .prefix = "LAK\xC2\xA0", .fraction_digits = 0 }, // LAK
    .{ .numeric = 422, .prefix = "LBP\xC2\xA0", .fraction_digits = 0 }, // LBP
    .{ .numeric = 426, .prefix = "LSL\xC2\xA0", .fraction_digits = 2 }, // LSL
    .{ .numeric = 430, .prefix = "LRD\xC2\xA0", .fraction_digits = 2 }, // LRD
    .{ .numeric = 434, .prefix = "LYD\xC2\xA0", .fraction_digits = 3 }, // LYD
    .{ .numeric = 446, .prefix = "MOP\xC2\xA0", .fraction_digits = 2 }, // MOP
    .{ .numeric = 454, .prefix = "MWK\xC2\xA0", .fraction_digits = 2 }, // MWK
    .{ .numeric = 458, .prefix = "MYR\xC2\xA0", .fraction_digits = 2 }, // MYR
    .{ .numeric = 462, .prefix = "MVR\xC2\xA0", .fraction_digits = 2 }, // MVR
    .{ .numeric = 480, .prefix = "MUR\xC2\xA0", .fraction_digits = 2 }, // MUR
    .{ .numeric = 484, .prefix = "MX$\xC2\xA0", .fraction_digits = 2 }, // MXN
    .{ .numeric = 496, .prefix = "MNT\xC2\xA0", .fraction_digits = 2 }, // MNT
    .{ .numeric = 498, .prefix = "MDL\xC2\xA0", .fraction_digits = 2 }, // MDL
    .{ .numeric = 504, .prefix = "MAD\xC2\xA0", .fraction_digits = 2 }, // MAD
    .{ .numeric = 512, .prefix = "OMR\xC2\xA0", .fraction_digits = 3 }, // OMR
    .{ .numeric = 516, .prefix = "NAD\xC2\xA0", .fraction_digits = 2 }, // NAD
    .{ .numeric = 524, .prefix = "NPR\xC2\xA0", .fraction_digits = 2 }, // NPR
    .{ .numeric = 532, .prefix = "Cg.\xC2\xA0", .fraction_digits = 2 }, // XCG
    .{ .numeric = 533, .prefix = "AWG\xC2\xA0", .fraction_digits = 2 }, // AWG
    .{ .numeric = 548, .prefix = "VUV\xC2\xA0", .fraction_digits = 0 }, // VUV
    .{ .numeric = 554, .prefix = "NZ$\xC2\xA0", .fraction_digits = 2 }, // NZD
    .{ .numeric = 558, .prefix = "NIO\xC2\xA0", .fraction_digits = 2 }, // NIO
    .{ .numeric = 566, .prefix = "NGN\xC2\xA0", .fraction_digits = 2 }, // NGN
    .{ .numeric = 578, .prefix = "NOK\xC2\xA0", .fraction_digits = 2 }, // NOK
    .{ .numeric = 586, .prefix = "PKR\xC2\xA0", .fraction_digits = 0 }, // PKR
    .{ .numeric = 590, .prefix = "PAB\xC2\xA0", .fraction_digits = 2 }, // PAB
    .{ .numeric = 598, .prefix = "PGK\xC2\xA0", .fraction_digits = 2 }, // PGK
    .{ .numeric = 600, .prefix = "PYG\xC2\xA0", .fraction_digits = 0 }, // PYG
    .{ .numeric = 604, .prefix = "PEN\xC2\xA0", .fraction_digits = 2 }, // PEN
    .{ .numeric = 608, .prefix = "PHP\xC2\xA0", .fraction_digits = 2 }, // PHP
    .{ .numeric = 634, .prefix = "QAR\xC2\xA0", .fraction_digits = 2 }, // QAR
    .{ .numeric = 643, .prefix = "RUB\xC2\xA0", .fraction_digits = 2 }, // RUB
    .{ .numeric = 646, .prefix = "RWF\xC2\xA0", .fraction_digits = 0 }, // RWF
    .{ .numeric = 654, .prefix = "SHP\xC2\xA0", .fraction_digits = 2 }, // SHP
    .{ .numeric = 682, .prefix = "SAR\xC2\xA0", .fraction_digits = 2 }, // SAR
    .{ .numeric = 690, .prefix = "SCR\xC2\xA0", .fraction_digits = 2 }, // SCR
    .{ .numeric = 702, .prefix = "SGD\xC2\xA0", .fraction_digits = 2 }, // SGD
    .{ .numeric = 704, .prefix = "\xE2\x82\xAB\xC2\xA0", .fraction_digits = 0 }, // VND
    .{ .numeric = 706, .prefix = "SOS\xC2\xA0", .fraction_digits = 0 }, // SOS
    .{ .numeric = 710, .prefix = "ZAR\xC2\xA0", .fraction_digits = 2 }, // ZAR
    .{ .numeric = 728, .prefix = "SSP\xC2\xA0", .fraction_digits = 2 }, // SSP
    .{ .numeric = 748, .prefix = "SZL\xC2\xA0", .fraction_digits = 2 }, // SZL
    .{ .numeric = 752, .prefix = "SEK\xC2\xA0", .fraction_digits = 2 }, // SEK
    .{ .numeric = 756, .prefix = "CHF\xC2\xA0", .fraction_digits = 2 }, // CHF
    .{ .numeric = 760, .prefix = "SYP\xC2\xA0", .fraction_digits = 0 }, // SYP
    .{ .numeric = 764, .prefix = "\xE0\xB8\xBF\xC2\xA0", .fraction_digits = 2 }, // THB
    .{ .numeric = 776, .prefix = "TOP\xC2\xA0", .fraction_digits = 2 }, // TOP
    .{ .numeric = 780, .prefix = "TTD\xC2\xA0", .fraction_digits = 2 }, // TTD
    .{ .numeric = 784, .prefix = "AED\xC2\xA0", .fraction_digits = 2 }, // AED
    .{ .numeric = 788, .prefix = "TND\xC2\xA0", .fraction_digits = 3 }, // TND
    .{ .numeric = 800, .prefix = "UGX\xC2\xA0", .fraction_digits = 0 }, // UGX
    .{ .numeric = 807, .prefix = "MKD\xC2\xA0", .fraction_digits = 2 }, // MKD
    .{ .numeric = 818, .prefix = "EGP\xC2\xA0", .fraction_digits = 2 }, // EGP
    .{ .numeric = 826, .prefix = "\xC2\xA3\xC2\xA0", .fraction_digits = 2 }, // GBP
    .{ .numeric = 834, .prefix = "TZS\xC2\xA0", .fraction_digits = 2 }, // TZS
    .{ .numeric = 840, .prefix = "US$\xC2\xA0", .fraction_digits = 2 }, // USD
    .{ .numeric = 858, .prefix = "UYU\xC2\xA0", .fraction_digits = 2 }, // UYU
    .{ .numeric = 860, .prefix = "UZS\xC2\xA0", .fraction_digits = 2 }, // UZS
    .{ .numeric = 882, .prefix = "WST\xC2\xA0", .fraction_digits = 2 }, // WST
    .{ .numeric = 886, .prefix = "YER\xC2\xA0", .fraction_digits = 0 }, // YER
    .{ .numeric = 901, .prefix = "NT$\xC2\xA0", .fraction_digits = 2 }, // TWD
    .{ .numeric = 924, .prefix = "ZWG\xC2\xA0", .fraction_digits = 2 }, // ZWG
    .{ .numeric = 925, .prefix = "SLE\xC2\xA0", .fraction_digits = 2 }, // SLE
    .{ .numeric = 926, .prefix = "VED\xC2\xA0", .fraction_digits = 2 }, // VED
    .{ .numeric = 928, .prefix = "VES\xC2\xA0", .fraction_digits = 2 }, // VES
    .{ .numeric = 929, .prefix = "MRU\xC2\xA0", .fraction_digits = 2 }, // MRU
    .{ .numeric = 930, .prefix = "STN\xC2\xA0", .fraction_digits = 2 }, // STN
    .{ .numeric = 933, .prefix = "BYN\xC2\xA0", .fraction_digits = 2 }, // BYN
    .{ .numeric = 934, .prefix = "TMT\xC2\xA0", .fraction_digits = 2 }, // TMT
    .{ .numeric = 936, .prefix = "GHS\xC2\xA0", .fraction_digits = 2 }, // GHS
    .{ .numeric = 938, .prefix = "SDG\xC2\xA0", .fraction_digits = 2 }, // SDG
    .{ .numeric = 941, .prefix = "RSD\xC2\xA0", .fraction_digits = 2 }, // RSD
    .{ .numeric = 943, .prefix = "MZN\xC2\xA0", .fraction_digits = 2 }, // MZN
    .{ .numeric = 944, .prefix = "AZN\xC2\xA0", .fraction_digits = 2 }, // AZN
    .{ .numeric = 946, .prefix = "RON\xC2\xA0", .fraction_digits = 2 }, // RON
    .{ .numeric = 949, .prefix = "TRY\xC2\xA0", .fraction_digits = 2 }, // TRY
    .{ .numeric = 950, .prefix = "FCFA\xC2\xA0", .fraction_digits = 0 }, // XAF
    .{ .numeric = 951, .prefix = "EC$\xC2\xA0", .fraction_digits = 2 }, // XCD
    .{ .numeric = 952, .prefix = "F\xE2\x80\xAFCFA\xC2\xA0", .fraction_digits = 0 }, // XOF
    .{ .numeric = 953, .prefix = "CFPF\xC2\xA0", .fraction_digits = 0 }, // XPF
    .{ .numeric = 960, .prefix = "XDR\xC2\xA0", .fraction_digits = 2 }, // XDR
    .{ .numeric = 967, .prefix = "ZMW\xC2\xA0", .fraction_digits = 2 }, // ZMW
    .{ .numeric = 968, .prefix = "SRD\xC2\xA0", .fraction_digits = 2 }, // SRD
    .{ .numeric = 969, .prefix = "MGA\xC2\xA0", .fraction_digits = 0 }, // MGA
    .{ .numeric = 971, .prefix = "AFN\xC2\xA0", .fraction_digits = 0 }, // AFN
    .{ .numeric = 972, .prefix = "TJS\xC2\xA0", .fraction_digits = 2 }, // TJS
    .{ .numeric = 973, .prefix = "AOA\xC2\xA0", .fraction_digits = 2 }, // AOA
    .{ .numeric = 976, .prefix = "CDF\xC2\xA0", .fraction_digits = 2 }, // CDF
    .{ .numeric = 977, .prefix = "BAM\xC2\xA0", .fraction_digits = 2 }, // BAM
    .{ .numeric = 978, .prefix = "\xE2\x82\xAC\xC2\xA0", .fraction_digits = 2 }, // EUR
    .{ .numeric = 980, .prefix = "UAH\xC2\xA0", .fraction_digits = 2 }, // UAH
    .{ .numeric = 981, .prefix = "GEL\xC2\xA0", .fraction_digits = 2 }, // GEL
    .{ .numeric = 985, .prefix = "PLN\xC2\xA0", .fraction_digits = 2 }, // PLN
    .{ .numeric = 986, .prefix = "R$\xC2\xA0", .fraction_digits = 2 }, // BRL
};
