// es-ES currency data pinned from Node 26.3.0 / ICU 78.3 / CLDR 48.0.
// Currency membership comes from ISO 4217 List One (2026-01-01): active
// country currencies plus XDR, excluding metals, testing, no-currency,
// fund, accounting-unit, and indexed-unit codes.
pub const Currency = struct {
    numeric: u32,
    suffix: []const u8,
    fraction_digits: u8,
};

pub const currencies = [_]Currency{
    .{ .numeric = 8, .suffix = "\xC2\xA0ALL", .fraction_digits = 0 }, // ALL
    .{ .numeric = 12, .suffix = "\xC2\xA0DZD", .fraction_digits = 2 }, // DZD
    .{ .numeric = 32, .suffix = "\xC2\xA0ARS", .fraction_digits = 2 }, // ARS
    .{ .numeric = 36, .suffix = "\xC2\xA0AUD", .fraction_digits = 2 }, // AUD
    .{ .numeric = 44, .suffix = "\xC2\xA0BSD", .fraction_digits = 2 }, // BSD
    .{ .numeric = 48, .suffix = "\xC2\xA0BHD", .fraction_digits = 3 }, // BHD
    .{ .numeric = 50, .suffix = "\xC2\xA0BDT", .fraction_digits = 2 }, // BDT
    .{ .numeric = 51, .suffix = "\xC2\xA0AMD", .fraction_digits = 2 }, // AMD
    .{ .numeric = 52, .suffix = "\xC2\xA0BBD", .fraction_digits = 2 }, // BBD
    .{ .numeric = 60, .suffix = "\xC2\xA0BMD", .fraction_digits = 2 }, // BMD
    .{ .numeric = 64, .suffix = "\xC2\xA0BTN", .fraction_digits = 2 }, // BTN
    .{ .numeric = 68, .suffix = "\xC2\xA0BOB", .fraction_digits = 2 }, // BOB
    .{ .numeric = 72, .suffix = "\xC2\xA0BWP", .fraction_digits = 2 }, // BWP
    .{ .numeric = 84, .suffix = "\xC2\xA0BZD", .fraction_digits = 2 }, // BZD
    .{ .numeric = 90, .suffix = "\xC2\xA0SBD", .fraction_digits = 2 }, // SBD
    .{ .numeric = 96, .suffix = "\xC2\xA0BND", .fraction_digits = 2 }, // BND
    .{ .numeric = 104, .suffix = "\xC2\xA0MMK", .fraction_digits = 0 }, // MMK
    .{ .numeric = 108, .suffix = "\xC2\xA0BIF", .fraction_digits = 0 }, // BIF
    .{ .numeric = 116, .suffix = "\xC2\xA0KHR", .fraction_digits = 2 }, // KHR
    .{ .numeric = 124, .suffix = "\xC2\xA0CAD", .fraction_digits = 2 }, // CAD
    .{ .numeric = 132, .suffix = "\xC2\xA0CVE", .fraction_digits = 2 }, // CVE
    .{ .numeric = 136, .suffix = "\xC2\xA0KYD", .fraction_digits = 2 }, // KYD
    .{ .numeric = 144, .suffix = "\xC2\xA0LKR", .fraction_digits = 2 }, // LKR
    .{ .numeric = 152, .suffix = "\xC2\xA0CLP", .fraction_digits = 0 }, // CLP
    .{ .numeric = 156, .suffix = "\xC2\xA0CNY", .fraction_digits = 2 }, // CNY
    .{ .numeric = 170, .suffix = "\xC2\xA0COP", .fraction_digits = 0 }, // COP
    .{ .numeric = 174, .suffix = "\xC2\xA0KMF", .fraction_digits = 0 }, // KMF
    .{ .numeric = 188, .suffix = "\xC2\xA0CRC", .fraction_digits = 2 }, // CRC
    .{ .numeric = 192, .suffix = "\xC2\xA0CUP", .fraction_digits = 2 }, // CUP
    .{ .numeric = 203, .suffix = "\xC2\xA0CZK", .fraction_digits = 2 }, // CZK
    .{ .numeric = 208, .suffix = "\xC2\xA0DKK", .fraction_digits = 2 }, // DKK
    .{ .numeric = 214, .suffix = "\xC2\xA0DOP", .fraction_digits = 2 }, // DOP
    .{ .numeric = 222, .suffix = "\xC2\xA0SVC", .fraction_digits = 2 }, // SVC
    .{ .numeric = 230, .suffix = "\xC2\xA0ETB", .fraction_digits = 2 }, // ETB
    .{ .numeric = 232, .suffix = "\xC2\xA0ERN", .fraction_digits = 2 }, // ERN
    .{ .numeric = 238, .suffix = "\xC2\xA0FKP", .fraction_digits = 2 }, // FKP
    .{ .numeric = 242, .suffix = "\xC2\xA0FJD", .fraction_digits = 2 }, // FJD
    .{ .numeric = 262, .suffix = "\xC2\xA0DJF", .fraction_digits = 0 }, // DJF
    .{ .numeric = 270, .suffix = "\xC2\xA0GMD", .fraction_digits = 2 }, // GMD
    .{ .numeric = 292, .suffix = "\xC2\xA0GIP", .fraction_digits = 2 }, // GIP
    .{ .numeric = 320, .suffix = "\xC2\xA0GTQ", .fraction_digits = 2 }, // GTQ
    .{ .numeric = 324, .suffix = "\xC2\xA0GNF", .fraction_digits = 0 }, // GNF
    .{ .numeric = 328, .suffix = "\xC2\xA0GYD", .fraction_digits = 2 }, // GYD
    .{ .numeric = 332, .suffix = "\xC2\xA0HTG", .fraction_digits = 2 }, // HTG
    .{ .numeric = 340, .suffix = "\xC2\xA0HNL", .fraction_digits = 2 }, // HNL
    .{ .numeric = 344, .suffix = "\xC2\xA0HKD", .fraction_digits = 2 }, // HKD
    .{ .numeric = 348, .suffix = "\xC2\xA0HUF", .fraction_digits = 0 }, // HUF
    .{ .numeric = 352, .suffix = "\xC2\xA0ISK", .fraction_digits = 0 }, // ISK
    .{ .numeric = 356, .suffix = "\xC2\xA0INR", .fraction_digits = 2 }, // INR
    .{ .numeric = 360, .suffix = "\xC2\xA0IDR", .fraction_digits = 0 }, // IDR
    .{ .numeric = 364, .suffix = "\xC2\xA0IRR", .fraction_digits = 0 }, // IRR
    .{ .numeric = 368, .suffix = "\xC2\xA0IQD", .fraction_digits = 0 }, // IQD
    .{ .numeric = 376, .suffix = "\xC2\xA0ILS", .fraction_digits = 2 }, // ILS
    .{ .numeric = 388, .suffix = "\xC2\xA0JMD", .fraction_digits = 2 }, // JMD
    .{ .numeric = 392, .suffix = "\xC2\xA0JPY", .fraction_digits = 0 }, // JPY
    .{ .numeric = 398, .suffix = "\xC2\xA0KZT", .fraction_digits = 2 }, // KZT
    .{ .numeric = 400, .suffix = "\xC2\xA0JOD", .fraction_digits = 3 }, // JOD
    .{ .numeric = 404, .suffix = "\xC2\xA0KES", .fraction_digits = 2 }, // KES
    .{ .numeric = 408, .suffix = "\xC2\xA0KPW", .fraction_digits = 0 }, // KPW
    .{ .numeric = 410, .suffix = "\xC2\xA0KRW", .fraction_digits = 0 }, // KRW
    .{ .numeric = 414, .suffix = "\xC2\xA0KWD", .fraction_digits = 3 }, // KWD
    .{ .numeric = 417, .suffix = "\xC2\xA0KGS", .fraction_digits = 2 }, // KGS
    .{ .numeric = 418, .suffix = "\xC2\xA0LAK", .fraction_digits = 0 }, // LAK
    .{ .numeric = 422, .suffix = "\xC2\xA0LBP", .fraction_digits = 0 }, // LBP
    .{ .numeric = 426, .suffix = "\xC2\xA0LSL", .fraction_digits = 2 }, // LSL
    .{ .numeric = 430, .suffix = "\xC2\xA0LRD", .fraction_digits = 2 }, // LRD
    .{ .numeric = 434, .suffix = "\xC2\xA0LYD", .fraction_digits = 3 }, // LYD
    .{ .numeric = 446, .suffix = "\xC2\xA0MOP", .fraction_digits = 2 }, // MOP
    .{ .numeric = 454, .suffix = "\xC2\xA0MWK", .fraction_digits = 2 }, // MWK
    .{ .numeric = 458, .suffix = "\xC2\xA0MYR", .fraction_digits = 2 }, // MYR
    .{ .numeric = 462, .suffix = "\xC2\xA0MVR", .fraction_digits = 2 }, // MVR
    .{ .numeric = 480, .suffix = "\xC2\xA0MUR", .fraction_digits = 2 }, // MUR
    .{ .numeric = 484, .suffix = "\xC2\xA0MXN", .fraction_digits = 2 }, // MXN
    .{ .numeric = 496, .suffix = "\xC2\xA0MNT", .fraction_digits = 2 }, // MNT
    .{ .numeric = 498, .suffix = "\xC2\xA0MDL", .fraction_digits = 2 }, // MDL
    .{ .numeric = 504, .suffix = "\xC2\xA0MAD", .fraction_digits = 2 }, // MAD
    .{ .numeric = 512, .suffix = "\xC2\xA0OMR", .fraction_digits = 3 }, // OMR
    .{ .numeric = 516, .suffix = "\xC2\xA0NAD", .fraction_digits = 2 }, // NAD
    .{ .numeric = 524, .suffix = "\xC2\xA0NPR", .fraction_digits = 2 }, // NPR
    .{ .numeric = 532, .suffix = "\xC2\xA0Cg.", .fraction_digits = 2 }, // XCG
    .{ .numeric = 533, .suffix = "\xC2\xA0AWG", .fraction_digits = 2 }, // AWG
    .{ .numeric = 548, .suffix = "\xC2\xA0VUV", .fraction_digits = 0 }, // VUV
    .{ .numeric = 554, .suffix = "\xC2\xA0NZD", .fraction_digits = 2 }, // NZD
    .{ .numeric = 558, .suffix = "\xC2\xA0NIO", .fraction_digits = 2 }, // NIO
    .{ .numeric = 566, .suffix = "\xC2\xA0NGN", .fraction_digits = 2 }, // NGN
    .{ .numeric = 578, .suffix = "\xC2\xA0NOK", .fraction_digits = 2 }, // NOK
    .{ .numeric = 586, .suffix = "\xC2\xA0PKR", .fraction_digits = 0 }, // PKR
    .{ .numeric = 590, .suffix = "\xC2\xA0PAB", .fraction_digits = 2 }, // PAB
    .{ .numeric = 598, .suffix = "\xC2\xA0PGK", .fraction_digits = 2 }, // PGK
    .{ .numeric = 600, .suffix = "\xC2\xA0PYG", .fraction_digits = 0 }, // PYG
    .{ .numeric = 604, .suffix = "\xC2\xA0PEN", .fraction_digits = 2 }, // PEN
    .{ .numeric = 608, .suffix = "\xC2\xA0PHP", .fraction_digits = 2 }, // PHP
    .{ .numeric = 634, .suffix = "\xC2\xA0QAR", .fraction_digits = 2 }, // QAR
    .{ .numeric = 643, .suffix = "\xC2\xA0RUB", .fraction_digits = 2 }, // RUB
    .{ .numeric = 646, .suffix = "\xC2\xA0RWF", .fraction_digits = 0 }, // RWF
    .{ .numeric = 654, .suffix = "\xC2\xA0SHP", .fraction_digits = 2 }, // SHP
    .{ .numeric = 682, .suffix = "\xC2\xA0SAR", .fraction_digits = 2 }, // SAR
    .{ .numeric = 690, .suffix = "\xC2\xA0SCR", .fraction_digits = 2 }, // SCR
    .{ .numeric = 702, .suffix = "\xC2\xA0SGD", .fraction_digits = 2 }, // SGD
    .{ .numeric = 704, .suffix = "\xC2\xA0\xE2\x82\xAB", .fraction_digits = 0 }, // VND
    .{ .numeric = 706, .suffix = "\xC2\xA0SOS", .fraction_digits = 0 }, // SOS
    .{ .numeric = 710, .suffix = "\xC2\xA0ZAR", .fraction_digits = 2 }, // ZAR
    .{ .numeric = 728, .suffix = "\xC2\xA0SSP", .fraction_digits = 2 }, // SSP
    .{ .numeric = 748, .suffix = "\xC2\xA0SZL", .fraction_digits = 2 }, // SZL
    .{ .numeric = 752, .suffix = "\xC2\xA0SEK", .fraction_digits = 2 }, // SEK
    .{ .numeric = 756, .suffix = "\xC2\xA0CHF", .fraction_digits = 2 }, // CHF
    .{ .numeric = 760, .suffix = "\xC2\xA0SYP", .fraction_digits = 0 }, // SYP
    .{ .numeric = 764, .suffix = "\xC2\xA0\xE0\xB8\xBF", .fraction_digits = 2 }, // THB
    .{ .numeric = 776, .suffix = "\xC2\xA0TOP", .fraction_digits = 2 }, // TOP
    .{ .numeric = 780, .suffix = "\xC2\xA0TTD", .fraction_digits = 2 }, // TTD
    .{ .numeric = 784, .suffix = "\xC2\xA0AED", .fraction_digits = 2 }, // AED
    .{ .numeric = 788, .suffix = "\xC2\xA0TND", .fraction_digits = 3 }, // TND
    .{ .numeric = 800, .suffix = "\xC2\xA0UGX", .fraction_digits = 0 }, // UGX
    .{ .numeric = 807, .suffix = "\xC2\xA0MKD", .fraction_digits = 2 }, // MKD
    .{ .numeric = 818, .suffix = "\xC2\xA0EGP", .fraction_digits = 2 }, // EGP
    .{ .numeric = 826, .suffix = "\xC2\xA0GBP", .fraction_digits = 2 }, // GBP
    .{ .numeric = 834, .suffix = "\xC2\xA0TZS", .fraction_digits = 2 }, // TZS
    .{ .numeric = 840, .suffix = "\xC2\xA0US$", .fraction_digits = 2 }, // USD
    .{ .numeric = 858, .suffix = "\xC2\xA0UYU", .fraction_digits = 2 }, // UYU
    .{ .numeric = 860, .suffix = "\xC2\xA0UZS", .fraction_digits = 2 }, // UZS
    .{ .numeric = 882, .suffix = "\xC2\xA0WST", .fraction_digits = 2 }, // WST
    .{ .numeric = 886, .suffix = "\xC2\xA0YER", .fraction_digits = 0 }, // YER
    .{ .numeric = 901, .suffix = "\xC2\xA0TWD", .fraction_digits = 2 }, // TWD
    .{ .numeric = 924, .suffix = "\xC2\xA0ZWG", .fraction_digits = 2 }, // ZWG
    .{ .numeric = 925, .suffix = "\xC2\xA0SLE", .fraction_digits = 2 }, // SLE
    .{ .numeric = 926, .suffix = "\xC2\xA0VED", .fraction_digits = 2 }, // VED
    .{ .numeric = 928, .suffix = "\xC2\xA0VES", .fraction_digits = 2 }, // VES
    .{ .numeric = 929, .suffix = "\xC2\xA0MRU", .fraction_digits = 2 }, // MRU
    .{ .numeric = 930, .suffix = "\xC2\xA0STN", .fraction_digits = 2 }, // STN
    .{ .numeric = 933, .suffix = "\xC2\xA0BYN", .fraction_digits = 2 }, // BYN
    .{ .numeric = 934, .suffix = "\xC2\xA0TMT", .fraction_digits = 2 }, // TMT
    .{ .numeric = 936, .suffix = "\xC2\xA0GHS", .fraction_digits = 2 }, // GHS
    .{ .numeric = 938, .suffix = "\xC2\xA0SDG", .fraction_digits = 2 }, // SDG
    .{ .numeric = 941, .suffix = "\xC2\xA0RSD", .fraction_digits = 2 }, // RSD
    .{ .numeric = 943, .suffix = "\xC2\xA0MZN", .fraction_digits = 2 }, // MZN
    .{ .numeric = 944, .suffix = "\xC2\xA0AZN", .fraction_digits = 2 }, // AZN
    .{ .numeric = 946, .suffix = "\xC2\xA0RON", .fraction_digits = 2 }, // RON
    .{ .numeric = 949, .suffix = "\xC2\xA0TRY", .fraction_digits = 2 }, // TRY
    .{ .numeric = 950, .suffix = "\xC2\xA0XAF", .fraction_digits = 0 }, // XAF
    .{ .numeric = 951, .suffix = "\xC2\xA0XCD", .fraction_digits = 2 }, // XCD
    .{ .numeric = 952, .suffix = "\xC2\xA0XOF", .fraction_digits = 0 }, // XOF
    .{ .numeric = 953, .suffix = "\xC2\xA0CFPF", .fraction_digits = 0 }, // XPF
    .{ .numeric = 960, .suffix = "\xC2\xA0XDR", .fraction_digits = 2 }, // XDR
    .{ .numeric = 967, .suffix = "\xC2\xA0ZMW", .fraction_digits = 2 }, // ZMW
    .{ .numeric = 968, .suffix = "\xC2\xA0SRD", .fraction_digits = 2 }, // SRD
    .{ .numeric = 969, .suffix = "\xC2\xA0MGA", .fraction_digits = 0 }, // MGA
    .{ .numeric = 971, .suffix = "\xC2\xA0AFN", .fraction_digits = 0 }, // AFN
    .{ .numeric = 972, .suffix = "\xC2\xA0TJS", .fraction_digits = 2 }, // TJS
    .{ .numeric = 973, .suffix = "\xC2\xA0AOA", .fraction_digits = 2 }, // AOA
    .{ .numeric = 976, .suffix = "\xC2\xA0CDF", .fraction_digits = 2 }, // CDF
    .{ .numeric = 977, .suffix = "\xC2\xA0BAM", .fraction_digits = 2 }, // BAM
    .{ .numeric = 978, .suffix = "\xC2\xA0\xE2\x82\xAC", .fraction_digits = 2 }, // EUR
    .{ .numeric = 980, .suffix = "\xC2\xA0UAH", .fraction_digits = 2 }, // UAH
    .{ .numeric = 981, .suffix = "\xC2\xA0GEL", .fraction_digits = 2 }, // GEL
    .{ .numeric = 985, .suffix = "\xC2\xA0PLN", .fraction_digits = 2 }, // PLN
    .{ .numeric = 986, .suffix = "\xC2\xA0BRL", .fraction_digits = 2 }, // BRL
};
