// Generated by tools/casegen from UCD 17.0.0 — do not edit.
// Curated inputs for compliance/unicode-17-uppercase.comply.zig. Inputs
// only: expected outputs come from the component's embedded oracle.

pub const Case = struct {
    name: []const u8,
    input: []const u8,
};

pub const cases = [_]Case{
    .{ .name = "empty", .input = "" },
    .{ .name = "ascii", .input = "Hello, World! qip 123" },
    .{ .name = "sharp-s", .input = "stra\xC3\x9Fe \xC3\x9F gro\xC3\x9F \xE1\xBA\x9E" },
    .{ .name = "ligatures", .input = "\xEF\xAC\x81 \xEF\xAC\x82 \xEF\xAC\x83 \xEF\xAC\x84 \xEF\xAC\x85 \xEF\xAC\x86 \xC7\xB3 \xC7\x86" },
    .{ .name = "apostrophe-n", .input = "\xC5\x89" },
    .{ .name = "greek-accents", .input = "\xCE\x90 \xCE\xB0 \xCE\xAD\xCE\xBE\xCE\xBF\xCF\x87\xCE\xAE \xCF\x83\xCE\xBF\xCF\x86\xCF\x8C\xCF\x82 \xCF\x82 \xCF\x83" },
    .{ .name = "ypogegrammeni", .input = "\xE1\xBE\x80 \xE1\xBE\xB7 \xE1\xBF\x83 \xE1\xBF\xB4 \xE1\xBE\xB3" },
    .{ .name = "dotless-dotted-i", .input = "i \xC4\xB1 \xC4\xB0 i\xCC\x87" },
    .{ .name = "titlecase-digraphs", .input = "\xC7\x85ungla \xC7\x88 \xC7\x8B" },
    .{ .name = "cherokee-small", .input = "\xEA\xAD\xB0\xEA\xAD\xB1\xEA\xAD\xB2 \xE1\x8F\xA3\xE1\x8E\xB3\xE1\x8E\xA9" },
    .{ .name = "deseret-plane1", .input = "\xF0\x90\x90\xA8\xF0\x90\x90\xA9" },
    .{ .name = "garay-unicode16", .input = "\xF0\x90\xB5\xB0\xF0\x90\xB5\xB1" },
    .{ .name = "mixed-scripts", .input = "\xD0\xBF\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82 \xCE\xB3\xCE\xB5\xCE\xB9\xCE\xB1 hello \xD0\xBC\xD0\xB8\xD1\x80" },
    .{ .name = "invalid-lone-ff", .input = "a\xFFb" },
    .{ .name = "invalid-truncated-c3", .input = "caf\xC3" },
    .{ .name = "invalid-lone-continuation", .input = "\x80\x81\xCF\x83" },
};
