const std = @import("std");

const INPUT_CAP: u32 = 0x20000;
const OUTPUT_CAP: u32 = 0x40000;

var input_buf: [INPUT_CAP]u8 = undefined;
var output_buf: [OUTPUT_CAP]u8 = undefined;

export fn input_ptr() u32 {
    return @as(u32, @intCast(@intFromPtr(&input_buf)));
}

export fn input_utf8_cap() u32 {
    return INPUT_CAP;
}

export fn output_ptr() u32 {
    return @as(u32, @intCast(@intFromPtr(&output_buf)));
}

export fn output_utf8_cap() u32 {
    return OUTPUT_CAP;
}

const EmojiEntry = struct {
    name: []const u8,
    emoji: []const u8,
};

const EmojiEntries = [_]EmojiEntry{
    .{ .name = "+1", .emoji = "👍" },
    .{ .name = "-1", .emoji = "👎" },
    .{ .name = "100", .emoji = "💯" },
    .{ .name = "1234", .emoji = "🔢" },
    .{ .name = "8ball", .emoji = "🎱" },
    .{ .name = "a", .emoji = "🅰️" },
    .{ .name = "ab", .emoji = "🆎" },
    .{ .name = "abc", .emoji = "🔤" },
    .{ .name = "ant", .emoji = "🐜" },
    .{ .name = "art", .emoji = "🎨" },
    .{ .name = "atm", .emoji = "🏧" },
    .{ .name = "abcd", .emoji = "🔡" },
    .{ .name = "alien", .emoji = "👽" },
    .{ .name = "angel", .emoji = "👼" },
    .{ .name = "anger", .emoji = "💢" },
    .{ .name = "angry", .emoji = "😠" },
    .{ .name = "apple", .emoji = "🍎" },
    .{ .name = "aries", .emoji = "♈" },
    .{ .name = "accept", .emoji = "🉑" },
    .{ .name = "anchor", .emoji = "⚓" },
    .{ .name = "airplane", .emoji = "✈️" },
    .{ .name = "aquarius", .emoji = "♒" },
    .{ .name = "arrow_up", .emoji = "⬆️" },
    .{ .name = "ambulance", .emoji = "🚑" },
    .{ .name = "anguished", .emoji = "😧" },
    .{ .name = "arrow_down", .emoji = "⬇️" },
    .{ .name = "arrow_left", .emoji = "⬅️" },
    .{ .name = "astonished", .emoji = "😲" },
    .{ .name = "alarm_clock", .emoji = "⏰" },
    .{ .name = "arrow_right", .emoji = "➡️" },
    .{ .name = "arrow_forward", .emoji = "▶️" },
    .{ .name = "arrow_up_down", .emoji = "↕️" },
    .{ .name = "aerial_tramway", .emoji = "🚡" },
    .{ .name = "arrow_backward", .emoji = "◀️" },
    .{ .name = "arrow_up_small", .emoji = "🔼" },
    .{ .name = "arrow_double_up", .emoji = "⏫" },
    .{ .name = "arrow_down_small", .emoji = "🔽" },
    .{ .name = "arrow_heading_up", .emoji = "⤴️" },
    .{ .name = "arrow_lower_left", .emoji = "↙️" },
    .{ .name = "arrow_right_hook", .emoji = "↪️" },
    .{ .name = "arrow_upper_left", .emoji = "↖️" },
    .{ .name = "arrows_clockwise", .emoji = "🔃" },
    .{ .name = "arrow_double_down", .emoji = "⏬" },
    .{ .name = "arrow_lower_right", .emoji = "↘️" },
    .{ .name = "arrow_upper_right", .emoji = "↗️" },
    .{ .name = "articulated_lorry", .emoji = "🚛" },
    .{ .name = "arrow_heading_down", .emoji = "⤵️" },
    .{ .name = "arrows_counterclockwise", .emoji = "🔄" },
    .{ .name = "b", .emoji = "🅱️" },
    .{ .name = "bow", .emoji = "🙇" },
    .{ .name = "boy", .emoji = "👦" },
    .{ .name = "bug", .emoji = "🐛" },
    .{ .name = "bus", .emoji = "🚌" },
    .{ .name = "baby", .emoji = "👶" },
    .{ .name = "bank", .emoji = "🏦" },
    .{ .name = "bath", .emoji = "🛀" },
    .{ .name = "bear", .emoji = "🐻" },
    .{ .name = "beer", .emoji = "🍺" },
    .{ .name = "bell", .emoji = "🔔" },
    .{ .name = "bike", .emoji = "🚲" },
    .{ .name = "bird", .emoji = "🐦" },
    .{ .name = "boar", .emoji = "🐗" },
    .{ .name = "boat", .emoji = "⛵" },
    .{ .name = "bomb", .emoji = "💣" },
    .{ .name = "book", .emoji = "📖" },
    .{ .name = "boom", .emoji = "💥" },
    .{ .name = "boot", .emoji = "👢" },
    .{ .name = "bulb", .emoji = "💡" },
    .{ .name = "beers", .emoji = "🍻" },
    .{ .name = "bento", .emoji = "🍱" },
    .{ .name = "blush", .emoji = "😊" },
    .{ .name = "books", .emoji = "📚" },
    .{ .name = "bread", .emoji = "🍞" },
    .{ .name = "bamboo", .emoji = "🎍" },
    .{ .name = "banana", .emoji = "🍌" },
    .{ .name = "barber", .emoji = "💈" },
    .{ .name = "beetle", .emoji = "🪲" },
    .{ .name = "bikini", .emoji = "👙" },
    .{ .name = "balloon", .emoji = "🎈" },
    .{ .name = "bathtub", .emoji = "🛁" },
    .{ .name = "battery", .emoji = "🔋" },
    .{ .name = "blossom", .emoji = "🌼" },
    .{ .name = "bouquet", .emoji = "💐" },
    .{ .name = "bowling", .emoji = "🎳" },
    .{ .name = "busstop", .emoji = "🚏" },
    .{ .name = "bangbang", .emoji = "‼️" },
    .{ .name = "baseball", .emoji = "⚾" },
    .{ .name = "beginner", .emoji = "🔰" },
    .{ .name = "birthday", .emoji = "🎂" },
    .{ .name = "blowfish", .emoji = "🐡" },
    .{ .name = "blue_car", .emoji = "🚙" },
    .{ .name = "bookmark", .emoji = "🔖" },
    .{ .name = "bar_chart", .emoji = "📊" },
    .{ .name = "bicyclist", .emoji = "🚴" },
    .{ .name = "black_nib", .emoji = "✒️" },
    .{ .name = "blue_book", .emoji = "📘" },
    .{ .name = "briefcase", .emoji = "💼" },
    .{ .name = "baby_chick", .emoji = "🐤" },
    .{ .name = "basketball", .emoji = "🏀" },
    .{ .name = "blue_heart", .emoji = "💙" },
    .{ .name = "baby_bottle", .emoji = "🍼" },
    .{ .name = "baby_symbol", .emoji = "🚼" },
    .{ .name = "black_joker", .emoji = "🃏" },
    .{ .name = "black_circle", .emoji = "⚫" },
    .{ .name = "broken_heart", .emoji = "💔" },
    .{ .name = "baggage_claim", .emoji = "🛄" },
    .{ .name = "bookmark_tabs", .emoji = "📑" },
    .{ .name = "bride_with_veil", .emoji = "👰‍♀️" },
    .{ .name = "bridge_at_night", .emoji = "🌉" },
    .{ .name = "bullettrain_side", .emoji = "🚄" },
    .{ .name = "bullettrain_front", .emoji = "🚅" },
    .{ .name = "bust_in_silhouette", .emoji = "👤" },
    .{ .name = "black_square_button", .emoji = "🔲" },
    .{ .name = "busts_in_silhouette", .emoji = "👥" },
    .{ .name = "ballot_box_with_check", .emoji = "☑️" },
    .{ .name = "cd", .emoji = "💿" },
    .{ .name = "cl", .emoji = "🆑" },
    .{ .name = "cn", .emoji = "🇨🇳" },
    .{ .name = "car", .emoji = "🚗" },
    .{ .name = "cat", .emoji = "🐱" },
    .{ .name = "cop", .emoji = "👮" },
    .{ .name = "cow", .emoji = "🐮" },
    .{ .name = "cry", .emoji = "😢" },
    .{ .name = "cake", .emoji = "🍰" },
    .{ .name = "cat2", .emoji = "🐈" },
    .{ .name = "clap", .emoji = "👏" },
    .{ .name = "cool", .emoji = "🆒" },
    .{ .name = "corn", .emoji = "🌽" },
    .{ .name = "cow2", .emoji = "🐄" },
    .{ .name = "camel", .emoji = "🐫" },
    .{ .name = "candy", .emoji = "🍬" },
    .{ .name = "chart", .emoji = "💹" },
    .{ .name = "cloud", .emoji = "☁️" },
    .{ .name = "clubs", .emoji = "♣️" },
    .{ .name = "crown", .emoji = "👑" },
    .{ .name = "cupid", .emoji = "💘" },
    .{ .name = "curry", .emoji = "🍛" },
    .{ .name = "cactus", .emoji = "🌵" },
    .{ .name = "camera", .emoji = "📷" },
    .{ .name = "cancer", .emoji = "♋" },
    .{ .name = "church", .emoji = "⛪" },
    .{ .name = "cinema", .emoji = "🎦" },
    .{ .name = "clock1", .emoji = "🕐" },
    .{ .name = "clock2", .emoji = "🕑" },
    .{ .name = "clock3", .emoji = "🕒" },
    .{ .name = "clock4", .emoji = "🕓" },
    .{ .name = "clock5", .emoji = "🕔" },
    .{ .name = "clock6", .emoji = "🕕" },
    .{ .name = "clock7", .emoji = "🕖" },
    .{ .name = "clock8", .emoji = "🕗" },
    .{ .name = "clock9", .emoji = "🕘" },
    .{ .name = "coffee", .emoji = "☕" },
    .{ .name = "cookie", .emoji = "🍪" },
    .{ .name = "couple", .emoji = "👫" },
    .{ .name = "calling", .emoji = "📲" },
    .{ .name = "chicken", .emoji = "🐔" },
    .{ .name = "clapper", .emoji = "🎬" },
    .{ .name = "clock10", .emoji = "🕙" },
    .{ .name = "clock11", .emoji = "🕚" },
    .{ .name = "clock12", .emoji = "🕛" },
    .{ .name = "custard", .emoji = "🍮" },
    .{ .name = "customs", .emoji = "🛃" },
    .{ .name = "cyclone", .emoji = "🌀" },
    .{ .name = "calendar", .emoji = "📆" },
    .{ .name = "cherries", .emoji = "🍒" },
    .{ .name = "chestnut", .emoji = "🌰" },
    .{ .name = "clock130", .emoji = "🕜" },
    .{ .name = "clock230", .emoji = "🕝" },
    .{ .name = "clock330", .emoji = "🕞" },
    .{ .name = "clock430", .emoji = "🕟" },
    .{ .name = "clock530", .emoji = "🕠" },
    .{ .name = "clock630", .emoji = "🕡" },
    .{ .name = "clock730", .emoji = "🕢" },
    .{ .name = "clock830", .emoji = "🕣" },
    .{ .name = "clock930", .emoji = "🕤" },
    .{ .name = "cocktail", .emoji = "🍸" },
    .{ .name = "computer", .emoji = "💻" },
    .{ .name = "confused", .emoji = "😕" },
    .{ .name = "capricorn", .emoji = "♑" },
    .{ .name = "clipboard", .emoji = "📋" },
    .{ .name = "clock1030", .emoji = "🕥" },
    .{ .name = "clock1130", .emoji = "🕦" },
    .{ .name = "clock1230", .emoji = "🕧" },
    .{ .name = "collision", .emoji = "💥" },
    .{ .name = "copyright", .emoji = "©️" },
    .{ .name = "crocodile", .emoji = "🐊" },
    .{ .name = "card_index", .emoji = "📇" },
    .{ .name = "cold_sweat", .emoji = "😰" },
    .{ .name = "confounded", .emoji = "😖" },
    .{ .name = "couplekiss", .emoji = "💏" },
    .{ .name = "curly_loop", .emoji = "➰" },
    .{ .name = "circus_tent", .emoji = "🎪" },
    .{ .name = "city_sunset", .emoji = "🌆" },
    .{ .name = "closed_book", .emoji = "📕" },
    .{ .name = "credit_card", .emoji = "💳" },
    .{ .name = "capital_abcd", .emoji = "🔠" },
    .{ .name = "city_sunrise", .emoji = "🌇" },
    .{ .name = "construction", .emoji = "🚧" },
    .{ .name = "crystal_ball", .emoji = "🔮" },
    .{ .name = "chocolate_bar", .emoji = "🍫" },
    .{ .name = "confetti_ball", .emoji = "🎊" },
    .{ .name = "crossed_flags", .emoji = "🎌" },
    .{ .name = "carousel_horse", .emoji = "🎠" },
    .{ .name = "checkered_flag", .emoji = "🏁" },
    .{ .name = "cherry_blossom", .emoji = "🌸" },
    .{ .name = "christmas_tree", .emoji = "🎄" },
    .{ .name = "closed_umbrella", .emoji = "🌂" },
    .{ .name = "congratulations", .emoji = "㊗️" },
    .{ .name = "crying_cat_face", .emoji = "😿" },
    .{ .name = "children_crossing", .emoji = "🚸" },
    .{ .name = "convenience_store", .emoji = "🏪" },
    .{ .name = "couple_with_heart", .emoji = "💑" },
    .{ .name = "currency_exchange", .emoji = "💱" },
    .{ .name = "construction_worker", .emoji = "👷" },
    .{ .name = "closed_lock_with_key", .emoji = "🔐" },
    .{ .name = "chart_with_upwards_trend", .emoji = "📈" },
    .{ .name = "chart_with_downwards_trend", .emoji = "📉" },
    .{ .name = "de", .emoji = "🇩🇪" },
    .{ .name = "dog", .emoji = "🐶" },
    .{ .name = "dvd", .emoji = "📀" },
    .{ .name = "dart", .emoji = "🎯" },
    .{ .name = "dash", .emoji = "💨" },
    .{ .name = "date", .emoji = "📅" },
    .{ .name = "dog2", .emoji = "🐕" },
    .{ .name = "door", .emoji = "🚪" },
    .{ .name = "dango", .emoji = "🍡" },
    .{ .name = "dizzy", .emoji = "💫" },
    .{ .name = "dolls", .emoji = "🎎" },
    .{ .name = "dress", .emoji = "👗" },
    .{ .name = "dancer", .emoji = "💃" },
    .{ .name = "dollar", .emoji = "💵" },
    .{ .name = "dragon", .emoji = "🐉" },
    .{ .name = "dancers", .emoji = "👯" },
    .{ .name = "dolphin", .emoji = "🐬" },
    .{ .name = "droplet", .emoji = "💧" },
    .{ .name = "diamonds", .emoji = "♦️" },
    .{ .name = "doughnut", .emoji = "🍩" },
    .{ .name = "dizzy_face", .emoji = "😵" },
    .{ .name = "dragon_face", .emoji = "🐲" },
    .{ .name = "disappointed", .emoji = "😞" },
    .{ .name = "do_not_litter", .emoji = "🚯" },
    .{ .name = "deciduous_tree", .emoji = "🌳" },
    .{ .name = "dromedary_camel", .emoji = "🐪" },
    .{ .name = "department_store", .emoji = "🏬" },
    .{ .name = "disappointed_relieved", .emoji = "😥" },
    .{ .name = "diamond_shape_with_a_dot_inside", .emoji = "💠" },
    .{ .name = "es", .emoji = "🇪🇸" },
    .{ .name = "ear", .emoji = "👂" },
    .{ .name = "egg", .emoji = "🥚" },
    .{ .name = "end", .emoji = "🔚" },
    .{ .name = "euro", .emoji = "💶" },
    .{ .name = "eyes", .emoji = "👀" },
    .{ .name = "eight", .emoji = "8️⃣" },
    .{ .name = "email", .emoji = "📧" },
    .{ .name = "e-mail", .emoji = "📧" },
    .{ .name = "eggplant", .emoji = "🍆" },
    .{ .name = "elephant", .emoji = "🐘" },
    .{ .name = "envelope", .emoji = "✉️" },
    .{ .name = "earth_asia", .emoji = "🌏" },
    .{ .name = "eyeglasses", .emoji = "👓" },
    .{ .name = "ear_of_rice", .emoji = "🌾" },
    .{ .name = "exclamation", .emoji = "❗" },
    .{ .name = "earth_africa", .emoji = "🌍" },
    .{ .name = "electric_plug", .emoji = "🔌" },
    .{ .name = "earth_americas", .emoji = "🌎" },
    .{ .name = "evergreen_tree", .emoji = "🌲" },
    .{ .name = "expressionless", .emoji = "😑" },
    .{ .name = "european_castle", .emoji = "🏰" },
    .{ .name = "european_post_office", .emoji = "🏤" },
    .{ .name = "eight_spoked_asterisk", .emoji = "✳️" },
    .{ .name = "eight_pointed_black_star", .emoji = "✴️" },
    .{ .name = "fr", .emoji = "🇫🇷" },
    .{ .name = "fu", .emoji = "🖕" },
    .{ .name = "fax", .emoji = "📠" },
    .{ .name = "feet", .emoji = "🐾" },
    .{ .name = "fire", .emoji = "🔥" },
    .{ .name = "fish", .emoji = "🐟" },
    .{ .name = "fist", .emoji = "✊" },
    .{ .name = "five", .emoji = "5️⃣" },
    .{ .name = "four", .emoji = "4️⃣" },
    .{ .name = "free", .emoji = "🆓" },
    .{ .name = "frog", .emoji = "🐸" },
    .{ .name = "flags", .emoji = "🎏" },
    .{ .name = "foggy", .emoji = "🌁" },
    .{ .name = "fries", .emoji = "🍟" },
    .{ .name = "family", .emoji = "👪" },
    .{ .name = "factory", .emoji = "🏭" },
    .{ .name = "fearful", .emoji = "😨" },
    .{ .name = "flushed", .emoji = "😳" },
    .{ .name = "football", .emoji = "🏈" },
    .{ .name = "fountain", .emoji = "⛲" },
    .{ .name = "frowning", .emoji = "😦" },
    .{ .name = "fuelpump", .emoji = "⛽" },
    .{ .name = "facepunch", .emoji = "👊" },
    .{ .name = "fireworks", .emoji = "🎆" },
    .{ .name = "fish_cake", .emoji = "🍥" },
    .{ .name = "full_moon", .emoji = "🌕" },
    .{ .name = "flashlight", .emoji = "🔦" },
    .{ .name = "fallen_leaf", .emoji = "🍂" },
    .{ .name = "file_folder", .emoji = "📁" },
    .{ .name = "fire_engine", .emoji = "🚒" },
    .{ .name = "floppy_disk", .emoji = "💾" },
    .{ .name = "fast_forward", .emoji = "⏩" },
    .{ .name = "ferris_wheel", .emoji = "🎡" },
    .{ .name = "fried_shrimp", .emoji = "🍤" },
    .{ .name = "fork_and_knife", .emoji = "🍴" },
    .{ .name = "four_leaf_clover", .emoji = "🍀" },
    .{ .name = "first_quarter_moon", .emoji = "🌓" },
    .{ .name = "full_moon_with_face", .emoji = "🌝" },
    .{ .name = "flower_playing_cards", .emoji = "🎴" },
    .{ .name = "fishing_pole_and_fish", .emoji = "🎣" },
    .{ .name = "first_quarter_moon_with_face", .emoji = "🌛" },
    .{ .name = "gb", .emoji = "🇬🇧" },
    .{ .name = "gem", .emoji = "💎" },
    .{ .name = "gun", .emoji = "🔫" },
    .{ .name = "gift", .emoji = "🎁" },
    .{ .name = "girl", .emoji = "👧" },
    .{ .name = "goat", .emoji = "🐐" },
    .{ .name = "golf", .emoji = "⛳" },
    .{ .name = "grin", .emoji = "😁" },
    .{ .name = "ghost", .emoji = "👻" },
    .{ .name = "gemini", .emoji = "♊" },
    .{ .name = "grapes", .emoji = "🍇" },
    .{ .name = "guitar", .emoji = "🎸" },
    .{ .name = "game_die", .emoji = "🎲" },
    .{ .name = "grinning", .emoji = "😀" },
    .{ .name = "grimacing", .emoji = "😬" },
    .{ .name = "guardsman", .emoji = "💂‍♂️" },
    .{ .name = "gift_heart", .emoji = "💝" },
    .{ .name = "green_book", .emoji = "📗" },
    .{ .name = "green_apple", .emoji = "🍏" },
    .{ .name = "green_heart", .emoji = "💚" },
    .{ .name = "grey_question", .emoji = "❔" },
    .{ .name = "grey_exclamation", .emoji = "❕" },
    .{ .name = "globe_with_meridians", .emoji = "🌐" },
    .{ .name = "hand", .emoji = "✋" },
    .{ .name = "hash", .emoji = "#️⃣" },
    .{ .name = "herb", .emoji = "🌿" },
    .{ .name = "heart", .emoji = "❤️" },
    .{ .name = "hocho", .emoji = "🔪" },
    .{ .name = "horse", .emoji = "🐴" },
    .{ .name = "hotel", .emoji = "🏨" },
    .{ .name = "house", .emoji = "🏠" },
    .{ .name = "hammer", .emoji = "🔨" },
    .{ .name = "hankey", .emoji = "💩" },
    .{ .name = "hearts", .emoji = "♥️" },
    .{ .name = "hushed", .emoji = "😯" },
    .{ .name = "haircut", .emoji = "💇" },
    .{ .name = "hamster", .emoji = "🐹" },
    .{ .name = "handbag", .emoji = "👜" },
    .{ .name = "hibiscus", .emoji = "🌺" },
    .{ .name = "honeybee", .emoji = "🐝" },
    .{ .name = "hospital", .emoji = "🏥" },
    .{ .name = "hamburger", .emoji = "🍔" },
    .{ .name = "heartbeat", .emoji = "💓" },
    .{ .name = "high_heel", .emoji = "👠" },
    .{ .name = "honey_pot", .emoji = "🍯" },
    .{ .name = "hourglass", .emoji = "⌛" },
    .{ .name = "headphones", .emoji = "🎧" },
    .{ .name = "heart_eyes", .emoji = "😍" },
    .{ .name = "heartpulse", .emoji = "💗" },
    .{ .name = "helicopter", .emoji = "🚁" },
    .{ .name = "hotsprings", .emoji = "♨️" },
    .{ .name = "hear_no_evil", .emoji = "🙉" },
    .{ .name = "horse_racing", .emoji = "🏇" },
    .{ .name = "hatched_chick", .emoji = "🐥" },
    .{ .name = "hatching_chick", .emoji = "🐣" },
    .{ .name = "heart_eyes_cat", .emoji = "😻" },
    .{ .name = "heavy_plus_sign", .emoji = "➕" },
    .{ .name = "high_brightness", .emoji = "🔆" },
    .{ .name = "heart_decoration", .emoji = "💟" },
    .{ .name = "heavy_check_mark", .emoji = "✔️" },
    .{ .name = "heavy_minus_sign", .emoji = "➖" },
    .{ .name = "heavy_dollar_sign", .emoji = "💲" },
    .{ .name = "house_with_garden", .emoji = "🏡" },
    .{ .name = "heavy_division_sign", .emoji = "➗" },
    .{ .name = "heavy_exclamation_mark", .emoji = "❗" },
    .{ .name = "heavy_multiplication_x", .emoji = "✖️" },
    .{ .name = "hourglass_flowing_sand", .emoji = "⏳" },
    .{ .name = "id", .emoji = "🆔" },
    .{ .name = "it", .emoji = "🇮🇹" },
    .{ .name = "imp", .emoji = "👿" },
    .{ .name = "iphone", .emoji = "📱" },
    .{ .name = "icecream", .emoji = "🍦" },
    .{ .name = "innocent", .emoji = "😇" },
    .{ .name = "ice_cream", .emoji = "🍨" },
    .{ .name = "inbox_tray", .emoji = "📥" },
    .{ .name = "interrobang", .emoji = "⁉️" },
    .{ .name = "izakaya_lantern", .emoji = "🏮" },
    .{ .name = "incoming_envelope", .emoji = "📨" },
    .{ .name = "information_source", .emoji = "ℹ️" },
    .{ .name = "ideograph_advantage", .emoji = "🉐" },
    .{ .name = "information_desk_person", .emoji = "💁" },
    .{ .name = "jp", .emoji = "🇯🇵" },
    .{ .name = "joy", .emoji = "😂" },
    .{ .name = "japan", .emoji = "🗾" },
    .{ .name = "jeans", .emoji = "👖" },
    .{ .name = "joy_cat", .emoji = "😹" },
    .{ .name = "japanese_ogre", .emoji = "👹" },
    .{ .name = "jack_o_lantern", .emoji = "🎃" },
    .{ .name = "japanese_castle", .emoji = "🏯" },
    .{ .name = "japanese_goblin", .emoji = "👺" },
    .{ .name = "kr", .emoji = "🇰🇷" },
    .{ .name = "key", .emoji = "🔑" },
    .{ .name = "kiss", .emoji = "💋" },
    .{ .name = "koko", .emoji = "🈁" },
    .{ .name = "koala", .emoji = "🐨" },
    .{ .name = "kimono", .emoji = "👘" },
    .{ .name = "kissing", .emoji = "😗" },
    .{ .name = "keycap_ten", .emoji = "🔟" },
    .{ .name = "kissing_cat", .emoji = "😽" },
    .{ .name = "kissing_heart", .emoji = "😘" },
    .{ .name = "kissing_closed_eyes", .emoji = "😚" },
    .{ .name = "kissing_smiling_eyes", .emoji = "😙" },
    .{ .name = "leo", .emoji = "♌" },
    .{ .name = "link", .emoji = "🔗" },
    .{ .name = "lips", .emoji = "👄" },
    .{ .name = "lock", .emoji = "🔒" },
    .{ .name = "loop", .emoji = "➿" },
    .{ .name = "lemon", .emoji = "🍋" },
    .{ .name = "libra", .emoji = "♎" },
    .{ .name = "leaves", .emoji = "🍃" },
    .{ .name = "ledger", .emoji = "📒" },
    .{ .name = "leopard", .emoji = "🐆" },
    .{ .name = "laughing", .emoji = "😆" },
    .{ .name = "lipstick", .emoji = "💄" },
    .{ .name = "lollipop", .emoji = "🍭" },
    .{ .name = "light_rail", .emoji = "🚈" },
    .{ .name = "love_hotel", .emoji = "🏩" },
    .{ .name = "loudspeaker", .emoji = "📢" },
    .{ .name = "love_letter", .emoji = "💌" },
    .{ .name = "left_luggage", .emoji = "🛅" },
    .{ .name = "low_brightness", .emoji = "🔅" },
    .{ .name = "left_right_arrow", .emoji = "↔️" },
    .{ .name = "large_blue_circle", .emoji = "🔵" },
    .{ .name = "last_quarter_moon", .emoji = "🌗" },
    .{ .name = "lock_with_ink_pen", .emoji = "🔏" },
    .{ .name = "large_blue_diamond", .emoji = "🔷" },
    .{ .name = "large_orange_diamond", .emoji = "🔶" },
    .{ .name = "leftwards_arrow_with_hook", .emoji = "↩️" },
    .{ .name = "last_quarter_moon_with_face", .emoji = "🌜" },
    .{ .name = "m", .emoji = "Ⓜ️" },
    .{ .name = "mag", .emoji = "🔍" },
    .{ .name = "man", .emoji = "👨" },
    .{ .name = "mask", .emoji = "😷" },
    .{ .name = "mega", .emoji = "📣" },
    .{ .name = "memo", .emoji = "📝" },
    .{ .name = "mens", .emoji = "🚹" },
    .{ .name = "moon", .emoji = "🌔" },
    .{ .name = "mute", .emoji = "🔇" },
    .{ .name = "melon", .emoji = "🍈" },
    .{ .name = "metal", .emoji = "🤘" },
    .{ .name = "metro", .emoji = "🚇" },
    .{ .name = "mouse", .emoji = "🐭" },
    .{ .name = "moyai", .emoji = "🗿" },
    .{ .name = "monkey", .emoji = "🐒" },
    .{ .name = "mouse2", .emoji = "🐁" },
    .{ .name = "muscle", .emoji = "💪" },
    .{ .name = "mahjong", .emoji = "🀄" },
    .{ .name = "mailbox", .emoji = "📫" },
    .{ .name = "massage", .emoji = "💆" },
    .{ .name = "minibus", .emoji = "🚐" },
    .{ .name = "minidisc", .emoji = "💽" },
    .{ .name = "moneybag", .emoji = "💰" },
    .{ .name = "monorail", .emoji = "🚝" },
    .{ .name = "mushroom", .emoji = "🍄" },
    .{ .name = "mag_right", .emoji = "🔎" },
    .{ .name = "mans_shoe", .emoji = "👞" },
    .{ .name = "milky_way", .emoji = "🌌" },
    .{ .name = "maple_leaf", .emoji = "🍁" },
    .{ .name = "microphone", .emoji = "🎤" },
    .{ .name = "microscope", .emoji = "🔬" },
    .{ .name = "mount_fuji", .emoji = "🗻" },
    .{ .name = "monkey_face", .emoji = "🐵" },
    .{ .name = "meat_on_bone", .emoji = "🍖" },
    .{ .name = "mortar_board", .emoji = "🎓" },
    .{ .name = "movie_camera", .emoji = "🎥" },
    .{ .name = "musical_note", .emoji = "🎵" },
    .{ .name = "musical_score", .emoji = "🎼" },
    .{ .name = "mailbox_closed", .emoji = "📪" },
    .{ .name = "man_with_turban", .emoji = "👳‍♂️" },
    .{ .name = "mobile_phone_off", .emoji = "📴" },
    .{ .name = "money_with_wings", .emoji = "💸" },
    .{ .name = "mountain_railway", .emoji = "🚞" },
    .{ .name = "musical_keyboard", .emoji = "🎹" },
    .{ .name = "mailbox_with_mail", .emoji = "📬" },
    .{ .name = "mountain_cableway", .emoji = "🚠" },
    .{ .name = "mountain_bicyclist", .emoji = "🚵" },
    .{ .name = "man_with_gua_pi_mao", .emoji = "👲" },
    .{ .name = "mailbox_with_no_mail", .emoji = "📭" },
    .{ .name = "ng", .emoji = "🆖" },
    .{ .name = "new", .emoji = "🆕" },
    .{ .name = "nine", .emoji = "9️⃣" },
    .{ .name = "nose", .emoji = "👃" },
    .{ .name = "notes", .emoji = "🎶" },
    .{ .name = "necktie", .emoji = "👔" },
    .{ .name = "no_bell", .emoji = "🔕" },
    .{ .name = "no_good", .emoji = "🙅" },
    .{ .name = "new_moon", .emoji = "🌑" },
    .{ .name = "no_entry", .emoji = "⛔" },
    .{ .name = "no_mouth", .emoji = "😶" },
    .{ .name = "notebook", .emoji = "📓" },
    .{ .name = "nail_care", .emoji = "💅" },
    .{ .name = "newspaper", .emoji = "📰" },
    .{ .name = "name_badge", .emoji = "📛" },
    .{ .name = "no_smoking", .emoji = "🚭" },
    .{ .name = "no_bicycles", .emoji = "🚳" },
    .{ .name = "neutral_face", .emoji = "😐" },
    .{ .name = "nut_and_bolt", .emoji = "🔩" },
    .{ .name = "no_entry_sign", .emoji = "🚫" },
    .{ .name = "no_pedestrians", .emoji = "🚷" },
    .{ .name = "no_mobile_phones", .emoji = "📵" },
    .{ .name = "non-potable_water", .emoji = "🚱" },
    .{ .name = "new_moon_with_face", .emoji = "🌚" },
    .{ .name = "negative_squared_cross_mark", .emoji = "❎" },
    .{ .name = "notebook_with_decorative_cover", .emoji = "📔" },
    .{ .name = "o", .emoji = "⭕" },
    .{ .name = "o2", .emoji = "🅾️" },
    .{ .name = "ok", .emoji = "🆗" },
    .{ .name = "on", .emoji = "🔛" },
    .{ .name = "ox", .emoji = "🐂" },
    .{ .name = "one", .emoji = "1️⃣" },
    .{ .name = "oden", .emoji = "🍢" },
    .{ .name = "ocean", .emoji = "🌊" },
    .{ .name = "office", .emoji = "🏢" },
    .{ .name = "octopus", .emoji = "🐙" },
    .{ .name = "ok_hand", .emoji = "👌" },
    .{ .name = "ok_woman", .emoji = "🙆‍♀️" },
    .{ .name = "older_man", .emoji = "👴" },
    .{ .name = "ophiuchus", .emoji = "⛎" },
    .{ .name = "open_hands", .emoji = "👐" },
    .{ .name = "open_mouth", .emoji = "😮" },
    .{ .name = "older_woman", .emoji = "👵" },
    .{ .name = "orange_book", .emoji = "📙" },
    .{ .name = "outbox_tray", .emoji = "📤" },
    .{ .name = "oncoming_bus", .emoji = "🚍" },
    .{ .name = "oncoming_taxi", .emoji = "🚖" },
    .{ .name = "open_file_folder", .emoji = "📂" },
    .{ .name = "oncoming_automobile", .emoji = "🚘" },
    .{ .name = "oncoming_police_car", .emoji = "🚔" },
    .{ .name = "pig", .emoji = "🐷" },
    .{ .name = "pear", .emoji = "🍐" },
    .{ .name = "pig2", .emoji = "🐖" },
    .{ .name = "pill", .emoji = "💊" },
    .{ .name = "poop", .emoji = "💩" },
    .{ .name = "pray", .emoji = "🙏" },
    .{ .name = "pager", .emoji = "📟" },
    .{ .name = "peach", .emoji = "🍑" },
    .{ .name = "phone", .emoji = "☎️" },
    .{ .name = "pizza", .emoji = "🍕" },
    .{ .name = "pouch", .emoji = "👝" },
    .{ .name = "pound", .emoji = "💷" },
    .{ .name = "punch", .emoji = "👊" },
    .{ .name = "purse", .emoji = "👛" },
    .{ .name = "pencil", .emoji = "📝" },
    .{ .name = "pisces", .emoji = "♓" },
    .{ .name = "poodle", .emoji = "🐩" },
    .{ .name = "parking", .emoji = "🅿️" },
    .{ .name = "pencil2", .emoji = "✏️" },
    .{ .name = "penguin", .emoji = "🐧" },
    .{ .name = "pensive", .emoji = "😔" },
    .{ .name = "postbox", .emoji = "📮" },
    .{ .name = "pushpin", .emoji = "📌" },
    .{ .name = "pig_nose", .emoji = "🐽" },
    .{ .name = "point_up", .emoji = "☝️" },
    .{ .name = "princess", .emoji = "👸" },
    .{ .name = "palm_tree", .emoji = "🌴" },
    .{ .name = "paperclip", .emoji = "📎" },
    .{ .name = "persevere", .emoji = "😣" },
    .{ .name = "pineapple", .emoji = "🍍" },
    .{ .name = "panda_face", .emoji = "🐼" },
    .{ .name = "paw_prints", .emoji = "🐾" },
    .{ .name = "point_down", .emoji = "👇" },
    .{ .name = "point_left", .emoji = "👈" },
    .{ .name = "point_up_2", .emoji = "👆" },
    .{ .name = "police_car", .emoji = "🚓" },
    .{ .name = "point_right", .emoji = "👉" },
    .{ .name = "post_office", .emoji = "🏣" },
    .{ .name = "postal_horn", .emoji = "📯" },
    .{ .name = "poultry_leg", .emoji = "🍗" },
    .{ .name = "pouting_cat", .emoji = "😾" },
    .{ .name = "partly_sunny", .emoji = "⛅" },
    .{ .name = "purple_heart", .emoji = "💜" },
    .{ .name = "potable_water", .emoji = "🚰" },
    .{ .name = "page_facing_up", .emoji = "📄" },
    .{ .name = "page_with_curl", .emoji = "📃" },
    .{ .name = "performing_arts", .emoji = "🎭" },
    .{ .name = "passport_control", .emoji = "🛂" },
    .{ .name = "part_alternation_mark", .emoji = "〽️" },
    .{ .name = "put_litter_in_its_place", .emoji = "🚮" },
    .{ .name = "question", .emoji = "❓" },
    .{ .name = "ru", .emoji = "🇷🇺" },
    .{ .name = "ram", .emoji = "🐏" },
    .{ .name = "rat", .emoji = "🐀" },
    .{ .name = "rage", .emoji = "😡" },
    .{ .name = "rice", .emoji = "🍚" },
    .{ .name = "ring", .emoji = "💍" },
    .{ .name = "rose", .emoji = "🌹" },
    .{ .name = "radio", .emoji = "📻" },
    .{ .name = "ramen", .emoji = "🍜" },
    .{ .name = "rabbit", .emoji = "🐰" },
    .{ .name = "repeat", .emoji = "🔁" },
    .{ .name = "rewind", .emoji = "⏪" },
    .{ .name = "ribbon", .emoji = "🎀" },
    .{ .name = "rocket", .emoji = "🚀" },
    .{ .name = "runner", .emoji = "🏃" },
    .{ .name = "rabbit2", .emoji = "🐇" },
    .{ .name = "rainbow", .emoji = "🌈" },
    .{ .name = "recycle", .emoji = "♻️" },
    .{ .name = "red_car", .emoji = "🚗" },
    .{ .name = "relaxed", .emoji = "☺️" },
    .{ .name = "rooster", .emoji = "🐓" },
    .{ .name = "rowboat", .emoji = "🚣" },
    .{ .name = "running", .emoji = "🏃" },
    .{ .name = "relieved", .emoji = "😌" },
    .{ .name = "restroom", .emoji = "🚻" },
    .{ .name = "racehorse", .emoji = "🐎" },
    .{ .name = "rice_ball", .emoji = "🍙" },
    .{ .name = "red_circle", .emoji = "🔴" },
    .{ .name = "registered", .emoji = "®️" },
    .{ .name = "repeat_one", .emoji = "🔂" },
    .{ .name = "rice_scene", .emoji = "🎑" },
    .{ .name = "railway_car", .emoji = "🚃" },
    .{ .name = "raised_hand", .emoji = "✋" },
    .{ .name = "radio_button", .emoji = "🔘" },
    .{ .name = "raised_hands", .emoji = "🙌" },
    .{ .name = "raising_hand", .emoji = "🙋" },
    .{ .name = "rice_cracker", .emoji = "🍘" },
    .{ .name = "round_pushpin", .emoji = "📍" },
    .{ .name = "roller_coaster", .emoji = "🎢" },
    .{ .name = "rotating_light", .emoji = "🚨" },
    .{ .name = "rugby_football", .emoji = "🏉" },
    .{ .name = "revolving_hearts", .emoji = "💞" },
    .{ .name = "running_shirt_with_sash", .emoji = "🎽" },
    .{ .name = "sa", .emoji = "🈂️" },
    .{ .name = "six", .emoji = "6️⃣" },
    .{ .name = "ski", .emoji = "🎿" },
    .{ .name = "sob", .emoji = "😭" },
    .{ .name = "sos", .emoji = "🆘" },
    .{ .name = "sake", .emoji = "🍶" },
    .{ .name = "seat", .emoji = "💺" },
    .{ .name = "ship", .emoji = "🚢" },
    .{ .name = "shit", .emoji = "💩" },
    .{ .name = "shoe", .emoji = "👞" },
    .{ .name = "soon", .emoji = "🔜" },
    .{ .name = "star", .emoji = "⭐" },
    .{ .name = "stew", .emoji = "🍲" },
    .{ .name = "santa", .emoji = "🎅" },
    .{ .name = "seven", .emoji = "7️⃣" },
    .{ .name = "sheep", .emoji = "🐑" },
    .{ .name = "shell", .emoji = "🐚" },
    .{ .name = "shirt", .emoji = "👕" },
    .{ .name = "skull", .emoji = "💀" },
    .{ .name = "smile", .emoji = "😄" },
    .{ .name = "smirk", .emoji = "😏" },
    .{ .name = "snail", .emoji = "🐌" },
    .{ .name = "snake", .emoji = "🐍" },
    .{ .name = "sound", .emoji = "🔉" },
    .{ .name = "star2", .emoji = "🌟" },
    .{ .name = "stars", .emoji = "🌠" },
    .{ .name = "sunny", .emoji = "☀️" },
    .{ .name = "sushi", .emoji = "🍣" },
    .{ .name = "sweat", .emoji = "😓" },
    .{ .name = "sandal", .emoji = "👡" },
    .{ .name = "school", .emoji = "🏫" },
    .{ .name = "scream", .emoji = "😱" },
    .{ .name = "scroll", .emoji = "📜" },
    .{ .name = "secret", .emoji = "㊙️" },
    .{ .name = "shower", .emoji = "🚿" },
    .{ .name = "sleepy", .emoji = "😪" },
    .{ .name = "smiley", .emoji = "😃" },
    .{ .name = "soccer", .emoji = "⚽" },
    .{ .name = "spades", .emoji = "♠️" },
    .{ .name = "surfer", .emoji = "🏄" },
    .{ .name = "smoking", .emoji = "🚬" },
    .{ .name = "snowman", .emoji = "⛄" },
    .{ .name = "speaker", .emoji = "🔈" },
    .{ .name = "station", .emoji = "🚉" },
    .{ .name = "sunrise", .emoji = "🌅" },
    .{ .name = "swimmer", .emoji = "🏊" },
    .{ .name = "symbols", .emoji = "🔣" },
    .{ .name = "syringe", .emoji = "💉" },
    .{ .name = "sailboat", .emoji = "⛵" },
    .{ .name = "scissors", .emoji = "✂️" },
    .{ .name = "scorpius", .emoji = "♏" },
    .{ .name = "seedling", .emoji = "🌱" },
    .{ .name = "sleeping", .emoji = "😴" },
    .{ .name = "sparkler", .emoji = "🎇" },
    .{ .name = "sparkles", .emoji = "✨" },
    .{ .name = "satellite", .emoji = "📡" },
    .{ .name = "satisfied", .emoji = "😆" },
    .{ .name = "saxophone", .emoji = "🎷" },
    .{ .name = "smile_cat", .emoji = "😸" },
    .{ .name = "smirk_cat", .emoji = "😼" },
    .{ .name = "snowflake", .emoji = "❄️" },
    .{ .name = "spaghetti", .emoji = "🍝" },
    .{ .name = "speedboat", .emoji = "🚤" },
    .{ .name = "sunflower", .emoji = "🌻" },
    .{ .name = "scream_cat", .emoji = "🙀" },
    .{ .name = "shaved_ice", .emoji = "🍧" },
    .{ .name = "smiley_cat", .emoji = "😺" },
    .{ .name = "strawberry", .emoji = "🍓" },
    .{ .name = "sunglasses", .emoji = "😎" },
    .{ .name = "sagittarius", .emoji = "♐" },
    .{ .name = "see_no_evil", .emoji = "🙈" },
    .{ .name = "smiling_imp", .emoji = "😈" },
    .{ .name = "snowboarder", .emoji = "🏂" },
    .{ .name = "sweat_drops", .emoji = "💦" },
    .{ .name = "sweat_smile", .emoji = "😅" },
    .{ .name = "slot_machine", .emoji = "🎰" },
    .{ .name = "sweet_potato", .emoji = "🍠" },
    .{ .name = "space_invader", .emoji = "👾" },
    .{ .name = "speak_no_evil", .emoji = "🙊" },
    .{ .name = "sun_with_face", .emoji = "🌞" },
    .{ .name = "school_satchel", .emoji = "🎒" },
    .{ .name = "speech_balloon", .emoji = "💬" },
    .{ .name = "straight_ruler", .emoji = "📏" },
    .{ .name = "signal_strength", .emoji = "📶" },
    .{ .name = "sparkling_heart", .emoji = "💖" },
    .{ .name = "six_pointed_star", .emoji = "🔯" },
    .{ .name = "steam_locomotive", .emoji = "🚂" },
    .{ .name = "stuck_out_tongue", .emoji = "😛" },
    .{ .name = "statue_of_liberty", .emoji = "🗽" },
    .{ .name = "small_blue_diamond", .emoji = "🔹" },
    .{ .name = "small_red_triangle", .emoji = "🔺" },
    .{ .name = "suspension_railway", .emoji = "🚟" },
    .{ .name = "small_orange_diamond", .emoji = "🔸" },
    .{ .name = "sunrise_over_mountains", .emoji = "🌄" },
    .{ .name = "small_red_triangle_down", .emoji = "🔻" },
    .{ .name = "stuck_out_tongue_closed_eyes", .emoji = "😝" },
    .{ .name = "stuck_out_tongue_winking_eye", .emoji = "😜" },
    .{ .name = "tm", .emoji = "™️" },
    .{ .name = "tv", .emoji = "📺" },
    .{ .name = "tea", .emoji = "🍵" },
    .{ .name = "top", .emoji = "🔝" },
    .{ .name = "two", .emoji = "2️⃣" },
    .{ .name = "tada", .emoji = "🎉" },
    .{ .name = "taxi", .emoji = "🚕" },
    .{ .name = "tent", .emoji = "⛺" },
    .{ .name = "tram", .emoji = "🚊" },
    .{ .name = "three", .emoji = "3️⃣" },
    .{ .name = "tiger", .emoji = "🐯" },
    .{ .name = "train", .emoji = "🚋" },
    .{ .name = "truck", .emoji = "🚚" },
    .{ .name = "tulip", .emoji = "🌷" },
    .{ .name = "taurus", .emoji = "♉" },
    .{ .name = "tennis", .emoji = "🎾" },
    .{ .name = "ticket", .emoji = "🎫" },
    .{ .name = "tiger2", .emoji = "🐅" },
    .{ .name = "toilet", .emoji = "🚽" },
    .{ .name = "tomato", .emoji = "🍅" },
    .{ .name = "tongue", .emoji = "👅" },
    .{ .name = "tophat", .emoji = "🎩" },
    .{ .name = "train2", .emoji = "🚆" },
    .{ .name = "trophy", .emoji = "🏆" },
    .{ .name = "tshirt", .emoji = "👕" },
    .{ .name = "turtle", .emoji = "🐢" },
    .{ .name = "tractor", .emoji = "🚜" },
    .{ .name = "trident", .emoji = "🔱" },
    .{ .name = "triumph", .emoji = "😤" },
    .{ .name = "trumpet", .emoji = "🎺" },
    .{ .name = "thumbsup", .emoji = "👍" },
    .{ .name = "tangerine", .emoji = "🍊" },
    .{ .name = "telephone", .emoji = "☎️" },
    .{ .name = "telescope", .emoji = "🔭" },
    .{ .name = "thumbsdown", .emoji = "👎" },
    .{ .name = "tired_face", .emoji = "😫" },
    .{ .name = "trolleybus", .emoji = "🚎" },
    .{ .name = "two_hearts", .emoji = "💕" },
    .{ .name = "tokyo_tower", .emoji = "🗼" },
    .{ .name = "tanabata_tree", .emoji = "🎋" },
    .{ .name = "traffic_light", .emoji = "🚥" },
    .{ .name = "tropical_fish", .emoji = "🐠" },
    .{ .name = "tropical_drink", .emoji = "🍹" },
    .{ .name = "thought_balloon", .emoji = "💭" },
    .{ .name = "triangular_ruler", .emoji = "📐" },
    .{ .name = "telephone_receiver", .emoji = "📞" },
    .{ .name = "two_men_holding_hands", .emoji = "👬" },
    .{ .name = "triangular_flag_on_post", .emoji = "🚩" },
    .{ .name = "two_women_holding_hands", .emoji = "👭" },
    .{ .name = "twisted_rightwards_arrows", .emoji = "🔀" },
    .{ .name = "uk", .emoji = "🇬🇧" },
    .{ .name = "up", .emoji = "🆙" },
    .{ .name = "us", .emoji = "🇺🇸" },
    .{ .name = "u5272", .emoji = "🈹" },
    .{ .name = "u5408", .emoji = "🈴" },
    .{ .name = "u55b6", .emoji = "🈺" },
    .{ .name = "u6307", .emoji = "🈯" },
    .{ .name = "u6708", .emoji = "🈷️" },
    .{ .name = "u6709", .emoji = "🈶" },
    .{ .name = "u6e80", .emoji = "🈵" },
    .{ .name = "u7121", .emoji = "🈚" },
    .{ .name = "u7533", .emoji = "🈸" },
    .{ .name = "u7981", .emoji = "🈲" },
    .{ .name = "u7a7a", .emoji = "🈳" },
    .{ .name = "unlock", .emoji = "🔓" },
    .{ .name = "umbrella", .emoji = "☔" },
    .{ .name = "unamused", .emoji = "😒" },
    .{ .name = "underage", .emoji = "🔞" },
    .{ .name = "v", .emoji = "✌️" },
    .{ .name = "vs", .emoji = "🆚" },
    .{ .name = "vhs", .emoji = "📼" },
    .{ .name = "virgo", .emoji = "♍" },
    .{ .name = "violin", .emoji = "🎻" },
    .{ .name = "volcano", .emoji = "🌋" },
    .{ .name = "video_game", .emoji = "🎮" },
    .{ .name = "video_camera", .emoji = "📹" },
    .{ .name = "vibration_mode", .emoji = "📳" },
    .{ .name = "vertical_traffic_light", .emoji = "🚦" },
    .{ .name = "wc", .emoji = "🚾" },
    .{ .name = "wave", .emoji = "👋" },
    .{ .name = "wink", .emoji = "😉" },
    .{ .name = "wolf", .emoji = "🐺" },
    .{ .name = "watch", .emoji = "⌚" },
    .{ .name = "weary", .emoji = "😩" },
    .{ .name = "whale", .emoji = "🐳" },
    .{ .name = "woman", .emoji = "👩" },
    .{ .name = "whale2", .emoji = "🐋" },
    .{ .name = "womens", .emoji = "🚺" },
    .{ .name = "wrench", .emoji = "🔧" },
    .{ .name = "walking", .emoji = "🚶" },
    .{ .name = "warning", .emoji = "⚠️" },
    .{ .name = "wedding", .emoji = "💒" },
    .{ .name = "worried", .emoji = "😟" },
    .{ .name = "wavy_dash", .emoji = "〰️" },
    .{ .name = "watermelon", .emoji = "🍉" },
    .{ .name = "wheelchair", .emoji = "♿" },
    .{ .name = "wind_chime", .emoji = "🎐" },
    .{ .name = "wine_glass", .emoji = "🍷" },
    .{ .name = "womans_hat", .emoji = "👒" },
    .{ .name = "white_circle", .emoji = "⚪" },
    .{ .name = "white_flower", .emoji = "💮" },
    .{ .name = "water_buffalo", .emoji = "🐃" },
    .{ .name = "womans_clothes", .emoji = "👚" },
    .{ .name = "white_check_mark", .emoji = "✅" },
    .{ .name = "waning_gibbous_moon", .emoji = "🌖" },
    .{ .name = "waxing_gibbous_moon", .emoji = "🌔" },
    .{ .name = "white_square_button", .emoji = "🔳" },
    .{ .name = "waning_crescent_moon", .emoji = "🌘" },
    .{ .name = "waxing_crescent_moon", .emoji = "🌒" },
    .{ .name = "x", .emoji = "❌" },
    .{ .name = "yen", .emoji = "💴" },
    .{ .name = "yum", .emoji = "😋" },
    .{ .name = "yellow_heart", .emoji = "💛" },
    .{ .name = "zap", .emoji = "⚡" },
    .{ .name = "zzz", .emoji = "💤" },
    .{ .name = "zero", .emoji = "0️⃣" },
};

fn shortcodeRange(first: u8) struct { start: usize, end: usize } {
    return switch (first) {
        '+' => .{ .start = 0, .end = 1 },
        '-' => .{ .start = 1, .end = 2 },
        '1' => .{ .start = 2, .end = 4 },
        '8' => .{ .start = 4, .end = 5 },
        'a' => .{ .start = 5, .end = 48 },
        'b' => .{ .start = 48, .end = 115 },
        'c' => .{ .start = 115, .end = 217 },
        'd' => .{ .start = 217, .end = 246 },
        'e' => .{ .start = 246, .end = 271 },
        'f' => .{ .start = 271, .end = 312 },
        'g' => .{ .start = 312, .end = 335 },
        'h' => .{ .start = 335, .end = 379 },
        'i' => .{ .start = 379, .end = 393 },
        'j' => .{ .start = 393, .end = 402 },
        'k' => .{ .start = 402, .end = 414 },
        'l' => .{ .start = 414, .end = 441 },
        'm' => .{ .start = 441, .end = 490 },
        'n' => .{ .start = 490, .end = 516 },
        'o' => .{ .start = 516, .end = 540 },
        'p' => .{ .start = 540, .end = 590 },
        'q' => .{ .start = 590, .end = 591 },
        'r' => .{ .start = 591, .end = 634 },
        's' => .{ .start = 634, .end = 731 },
        't' => .{ .start = 731, .end = 781 },
        'u' => .{ .start = 781, .end = 799 },
        'v' => .{ .start = 799, .end = 809 },
        'w' => .{ .start = 809, .end = 840 },
        'x' => .{ .start = 840, .end = 841 },
        'y' => .{ .start = 841, .end = 844 },
        'z' => .{ .start = 844, .end = 847 },
        else => .{ .start = 0, .end = 0 },
    };
}

fn shortcodeNameEqual(input: []const u8, name: []const u8) bool {
    if (input.len != name.len) return false;
    var i: usize = 0;
    while (i < input.len) : (i += 1) {
        if (input[i] != name[i]) return false;
    }
    return true;
}

fn lookupEmoji(name: []const u8) ?[]const u8 {
    if (name.len == 0) return null;
    const range = shortcodeRange(name[0]);
    var i = range.start;
    while (i < range.end) : (i += 1) {
        const entry = EmojiEntries[i];
        if (shortcodeNameEqual(name, entry.name)) return entry.emoji;
    }
    return null;
}

const Writer = struct {
    buf: []u8,
    idx: usize,

    fn init(buf: []u8) Writer {
        return .{ .buf = buf, .idx = 0 };
    }

    fn writeByte(self: *Writer, b: u8) void {
        if (self.idx >= self.buf.len) {
            @trap();
        }
        self.buf[self.idx] = b;
        self.idx += 1;
    }

    fn writeSlice(self: *Writer, s: []const u8) void {
        if (self.idx + s.len > self.buf.len) {
            @trap();
        }
        @memcpy(self.buf[self.idx .. self.idx + s.len], s);
        self.idx += s.len;
    }
};

fn isShortcodeChar(ch: u8) bool {
    return std.ascii.isAlphanumeric(ch) or ch == '_' or ch == '+' or ch == '-';
}

export fn render(input_size: u32) u32 {
    const input = input_buf[0..@as(usize, @intCast(input_size))];
    var w = Writer.init(output_buf[0..]);
    var i: usize = 0;
    while (i < input.len) {
        if (input[i] == ':') {
            const start = i;
            i += 1;
            var j = i;
            while (j < input.len and isShortcodeChar(input[j])) : (j += 1) {}
            if (j < input.len and input[j] == ':' and j > i) {
                const name = input[i..j];
                if (lookupEmoji(name)) |emoji| {
                    w.writeSlice(emoji);
                    i = j + 1;
                    continue;
                }
            }
            w.writeByte(':');
            i = start + 1;
            continue;
        }
        w.writeByte(input[i]);
        i += 1;
    }
    return @as(u32, @intCast(w.idx));
}

test "shortcode replace" {
    var out: [256]u8 = undefined;
    const input = "Hello :smile: world";
    const written = runString(input, out[0..]);
    try std.testing.expectEqualStrings("Hello 😄 world", out[0..written]);
}

test "unknown shortcode" {
    var out: [256]u8 = undefined;
    const input = "Hi :notreal: there";
    const written = runString(input, out[0..]);
    try std.testing.expectEqualStrings("Hi :notreal: there", out[0..written]);
}

test "custom emoji remains" {
    var out: [256]u8 = undefined;
    const input = "Ship :octocat:";
    const written = runString(input, out[0..]);
    try std.testing.expectEqualStrings("Ship :octocat:", out[0..written]);
}

fn runString(input: []const u8, out: []u8) usize {
    @memcpy(input_buf[0..input.len], input);
    const written = render(@as(u32, @intCast(input.len)));
    @memcpy(out[0..written], output_buf[0..written]);
    return @as(usize, @intCast(written));
}
