#!/usr/bin/env python3
"""Generates the HTML5 named-entity and Unicode case-fold tables used by the
markdown components and their compliance checkers.

Inputs (vendored, pinned):
  tools/html5-entities.json
    https://html.spec.whatwg.org/entities.json
    sha256 d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6
  tools/casegen/ucd-17.0.0/CaseFolding.txt
    https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt
    sha256 ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183

Outputs (each written twice — component copy and compliance copy):
  components/text/markdown/lib/html5-entities-table.zig
  compliance/html5-entities-table.zig
  components/text/markdown/lib/unicode-17-casefold-tables.zig
  compliance/unicode-17-casefold-tables.zig

Usage: python3 tools/generate-markdown-tables.py (from the repo root)
"""

import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

ENTITIES_JSON = ROOT / "tools" / "html5-entities.json"
CASE_FOLDING = ROOT / "tools" / "casegen" / "ucd-17.0.0" / "CaseFolding.txt"

ENTITIES_SHA = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
CASE_FOLDING_SHA = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"

GENERATED_NOTE = "// Generated by tools/generate-markdown-tables.py — do not edit."


def check_sha(path, expected):
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != expected:
        sys.exit(f"{path}: sha256 {digest} does not match pinned {expected}")


def zig_string_literal(data: bytes) -> str:
    out = []
    for b in data:
        if b in (0x22, 0x5C):  # " and backslash
            out.append("\\" + chr(b))
        elif 0x20 <= b <= 0x7E:
            out.append(chr(b))
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x09:
            out.append("\\t")
        else:
            out.append(f"\\x{b:02x}")
    return '"' + "".join(out) + '"'


def wrap_ints(values, fmt, per_line):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(fmt(v) for v in values[i : i + per_line])
        lines.append("    " + chunk + ",")
    return "\n".join(lines)


def wrap_string(data: bytes, chunk_size=64):
    lines = []
    for i in range(0, len(data), chunk_size):
        lines.append("    " + zig_string_literal(data[i : i + chunk_size]) + " ++")
    if not lines:
        return '    ""'
    lines[-1] = lines[-1][: -len(" ++")]
    return "\n".join(lines)


def generate_entities() -> str:
    entities = json.loads(ENTITIES_JSON.read_text())
    entries = sorted(
        (name[1:-1], info["characters"].encode())
        for name, info in entities.items()
        if name.endswith(";")
    )
    names_blob = b"".join(name.encode() for name, _ in entries)
    values_blob = b"".join(value for _, value in entries)
    assert len(names_blob) < 0x10000 and len(values_blob) < 0x10000
    name_ends, value_ends = [], []
    n = v = 0
    for name, value in entries:
        n += len(name)
        v += len(value)
        name_ends.append(n)
        value_ends.append(v)
    return f"""{GENERATED_NOTE}
// HTML5 named character references that end in a semicolon — the set
// CommonMark 0.31.2 requires — from entities.json (WHATWG HTML), pinned in
// tools/generate-markdown-tables.py. {len(entries)} entries, sorted bytewise
// by name (without the leading "&" or trailing ";"). Entry i's name is
// names_blob[start..name_ends[i]] and its replacement text is
// values_blob[start..value_ends[i]], where start is the previous entry's end.
pub const count: usize = {len(entries)};

pub const names_blob =
{wrap_string(names_blob)};

pub const name_ends = [_]u16{{
{wrap_ints(name_ends, lambda x: str(x), 14)}
}};

pub const values_blob =
{wrap_string(values_blob)};

pub const value_ends = [_]u16{{
{wrap_ints(value_ends, lambda x: str(x), 14)}
}};
"""


def generate_casefold() -> str:
    singles, multis = [], []
    for line in CASE_FOLDING.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        cp, status, mapping = int(fields[0], 16), fields[1], fields[2]
        if status == "C":
            singles.append((cp, int(mapping, 16)))
        elif status == "F":
            multis.append((cp, [int(c, 16) for c in mapping.split()]))
    singles.sort()
    multis.sort()
    assert all(len(m) <= 3 for _, m in multis)
    multi_rows = ",\n".join(
        "    .{ " + ", ".join(f"0x{c:X}" for c in (m + [0, 0, 0])[:3]) + " }"
        for _, m in multis
    )
    return f"""{GENERATED_NOTE}
// Unicode 17.0.0 case folding (CaseFolding.txt statuses C and F — the full,
// non-Turkic fold CommonMark requires for reference-label matching), pinned in
// tools/generate-markdown-tables.py. fold_map_* holds the 1:1 common folds;
// fold_multi_* holds the full folds that expand to 2-3 code points
// (zero-padded). Both key arrays are sorted for binary search.
pub const fold_map_keys = [_]u32{{
{wrap_ints([k for k, _ in singles], lambda x: f"0x{x:X}", 12)}
}};

pub const fold_map_values = [_]u32{{
{wrap_ints([v for _, v in singles], lambda x: f"0x{x:X}", 12)}
}};

pub const fold_multi_keys = [_]u32{{
{wrap_ints([k for k, _ in multis], lambda x: f"0x{x:X}", 12)}
}};

pub const fold_multi_values = [_][3]u32{{
{multi_rows},
}};
"""


def main():
    check_sha(ENTITIES_JSON, ENTITIES_SHA)
    check_sha(CASE_FOLDING, CASE_FOLDING_SHA)
    entities = generate_entities()
    casefold = generate_casefold()
    targets = [
        (ROOT / "components/text/markdown/lib/html5-entities-table.zig", entities),
        (ROOT / "compliance/html5-entities-table.zig", entities),
        (ROOT / "components/text/markdown/lib/unicode-17-casefold-tables.zig", casefold),
        (ROOT / "compliance/unicode-17-casefold-tables.zig", casefold),
    ]
    for path, content in targets:
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
