// Unicode 17.0.0 Default Case Conversion uppercase (und root — byte-identical
// for every tag without a casing tailoring; only tr/az and lt differ and
// would be separate components).
// Full mappings from UnicodeData + unconditional SpecialCasing (ß -> SS,
// ligatures -> letter sequences, ypogegrammeni -> prosgegrammeni). Unicode
// default uppercase has no context rules, unlike lowercase's Final_Sigma.
// Invalid UTF-8 bytes are copied through unchanged as uncased characters.
// Conformance: compliance/unicode-17-uppercase.comply.wasm.
// Tables generated by tools/casegen.
const tables = @import("lib/unicode-17-uppercase-tables.zig");
const utf8 = @import("lib/utf8.zig");

const INPUT_CAP: usize = 64 * 1024;
// Worst-case growth is 3x (e.g. U+0390, 2 bytes -> U+0399 U+0308 U+0301, 6 bytes).
const OUTPUT_CAP: usize = 192 * 1024;

var input_buf: [INPUT_CAP]u8 = undefined;
var output_buf: [OUTPUT_CAP]u8 = undefined;

export fn input_ptr() u32 {
    return @as(u32, @intCast(@intFromPtr(&input_buf)));
}

export fn input_utf8_cap() u32 {
    return @as(u32, @intCast(INPUT_CAP));
}

export fn output_ptr() u32 {
    return @as(u32, @intCast(@intFromPtr(&output_buf)));
}

export fn output_utf8_cap() u32 {
    return @as(u32, @intCast(OUTPUT_CAP));
}

// Returns the mapped UTF-8 bytes, or null when cp uppercases to itself.
fn lookupUpper(cp: u32) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = tables.map_keys.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (tables.map_keys[mid] < cp) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    if (lo >= tables.map_keys.len or tables.map_keys[lo] != cp) return null;
    const packed_val = tables.map_packed[lo];
    const off = packed_val >> 8;
    const len = packed_val & 0xFF;
    return tables.map_blob[off .. off + len];
}

fn emit(out: *usize, bytes: []const u8) void {
    if (out.* + bytes.len > OUTPUT_CAP) @panic("output buffer overflow");
    for (bytes) |b| {
        output_buf[out.*] = b;
        out.* += 1;
    }
}

export fn render(input_size_in: u32) u32 {
    const input_size: usize = @intCast(input_size_in);
    if (input_size > INPUT_CAP) @panic("input larger than input_utf8_cap");

    const input = input_buf[0..input_size];
    var out: usize = 0;

    var i: usize = 0;
    while (i < input_size) {
        const d = utf8.decode(input[i..]);

        if (!d.valid) {
            emit(&out, input[i .. i + 1]);
            i += 1;
            continue;
        }

        if (lookupUpper(d.cp)) |upper| {
            emit(&out, upper);
        } else {
            emit(&out, input[i .. i + d.size]);
        }

        i += d.size;
    }

    return @as(u32, @intCast(out));
}
